import type { RecipeContent } from '../../domain/food/recipe'

export const recipesB: RecipeContent[] = [
  {
    id: 'gujarati-undhiyu',
    name: 'Gujarati Undhiyu',
    cuisine: 'Gujarati',
    dietMode: 'vegan',
    description:
      'Surat’s winter one-pot of beans, yam, sweet potato and fenugreek dumplings slow-cooked in a green coconut, coriander and peanut masala.',
    servings: 4,
    prepMinutes: 45,
    cookMinutes: 50,
    difficulty: 'involved',
    spice: 'medium',
    protein: 'medium',
    costBand: '₹₹',
    tags: ['Regional', 'Weekend', 'One-pot'],
    ingredients: [
      { qty: 1, unit: 'cup', item: 'besan (gram flour)', note: 'for the muthia' },
      { qty: 2, unit: 'tbsp', item: 'whole wheat flour (atta)', note: 'for the muthia' },
      { qty: 1, unit: 'cup', item: 'fresh methi (fenugreek) leaves', note: 'finely chopped' },
      { qty: 0.5, unit: 'tsp', item: 'baking soda', note: 'for the muthia' },
      { qty: 250, unit: 'g', item: 'surti papdi (flat beans)', note: 'strings removed, halved' },
      { qty: 150, unit: 'g', item: 'purple yam (kand)', note: 'peeled, 1-inch cubes' },
      { qty: 1, unit: 'piece', item: 'sweet potato (medium)', note: 'peeled, 1-inch cubes' },
      { qty: 2, unit: 'piece', item: 'baby potatoes', note: 'halved' },
      { qty: 1, unit: 'piece', item: 'raw banana', note: 'peeled, thick rounds' },
      { qty: 4, unit: 'piece', item: 'small brinjals (baingan)', note: 'slit in a cross, stems on' },
      { qty: 0.5, unit: 'cup', item: 'fresh grated coconut' },
      { qty: 1, unit: 'cup', item: 'coriander leaves', note: 'packed, chopped' },
      { qty: 3, unit: 'tbsp', item: 'roasted peanuts', note: 'coarsely crushed' },
      { qty: 3, unit: 'piece', item: 'green chillies' },
      { qty: 1, unit: 'inch', item: 'ginger' },
      { qty: 4, unit: 'clove', item: 'garlic' },
      { qty: 1, unit: 'tbsp', item: 'jaggery', note: 'grated' },
      { qty: 1, unit: 'tbsp', item: 'lemon juice' },
      { qty: 1, unit: 'tsp', item: 'sesame seeds' },
      { qty: 0.5, unit: 'tsp', item: 'turmeric powder' },
      { qty: 1, unit: 'tsp', item: 'red chilli powder' },
      { qty: 1, unit: 'tsp', item: 'ajwain (carom seeds)' },
      { qty: 0.25, unit: 'tsp', item: 'asafoetida (hing)' },
      { qty: 5, unit: 'tbsp', item: 'groundnut oil', note: 'plus extra for frying muthia' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'Make the muthia dough: mix besan, atta, chopped methi, a pinch of ajwain, half the red chilli powder, a pinch of soda, salt and 1 tbsp oil, adding water a spoon at a time until it forms a soft, slightly sticky dough.',
      },
      {
        text: 'Wet your palms and roll the dough into small finger-length dumplings, then shallow-fry them in hot oil over medium heat, turning, until deep golden and cooked through; drain and set aside.',
        timerMin: 8,
      },
      {
        text: 'Grind the coconut, coriander, peanuts, green chillies, ginger, garlic, sesame seeds, jaggery, lemon juice, turmeric, the remaining chilli powder and salt into a coarse, moist green masala without adding water.',
      },
      {
        text: 'Stuff the slit brinjals with about two tablespoons of the green masala, then toss the remaining masala with the yam, sweet potato, potatoes, raw banana and papdi so every piece is coated.',
      },
      {
        text: 'Heat 3 tbsp oil in a heavy-bottomed pot on medium, add the remaining ajwain and the asafoetida and let them sizzle for 10 seconds.',
      },
      {
        text: 'Layer the papdi at the bottom, then the root vegetables, then the stuffed brinjals on top; sprinkle half a cup of water around the edges, cover tightly and cook on low heat without stirring.',
        timerMin: 25,
      },
      {
        text: 'Gently shake the pot (do not stir hard, or the vegetables will break), check that the yam and sweet potato are tender when pierced with a knife, and add a splash of water only if the base is catching.',
        timerMin: 10,
      },
      {
        text: 'Tuck the fried muthia into the pot, cover and cook for 5 more minutes on low so they soak up the masala, then rest off the heat for 5 minutes before serving with puris or rotlis.',
        timerMin: 5,
      },
    ],
    nutrition: { kcal: 520, proteinG: 14, carbsG: 58, fatG: 26, fibreG: 12 },
  },
  {
    id: 'gujarati-khichdi-kadhi',
    name: 'Gujarati Khichdi Kadhi (Jain-friendly)',
    cuisine: 'Gujarati',
    dietMode: 'vegetarian',
    description:
      'Soft ghee-laced rice and moong dal khichdi with a sweet-sour Gujarati kadhi, made without onion, garlic or any root vegetables.',
    servings: 3,
    prepMinutes: 10,
    cookMinutes: 25,
    difficulty: 'easy',
    spice: 'mild',
    protein: 'medium',
    costBand: '₹',
    tags: ['Jain-friendly', 'Regional', 'Budget', 'Kid-friendly'],
    ingredients: [
      { qty: 0.5, unit: 'cup', item: 'rice (short-grain or sona masuri)', note: 'rinsed' },
      { qty: 0.5, unit: 'cup', item: 'split yellow moong dal', note: 'rinsed, soaked 15 minutes' },
      { qty: 0.25, unit: 'tsp', item: 'turmeric powder' },
      { qty: 2, unit: 'tbsp', item: 'ghee', note: 'divided' },
      { qty: 1, unit: 'cup', item: 'curd', note: 'slightly sour, at room temperature' },
      { qty: 2, unit: 'tbsp', item: 'besan (gram flour)' },
      { qty: 2, unit: 'cup', item: 'water', note: 'for the kadhi' },
      { qty: 1, unit: 'tbsp', item: 'jaggery', note: 'grated, adjust to taste' },
      { qty: 1, unit: 'piece', item: 'green chilli', note: 'slit' },
      { qty: 0.25, unit: 'tsp', item: 'dry ginger powder (sonth)' },
      { qty: 1, unit: 'tsp', item: 'cumin seeds' },
      { qty: 0.5, unit: 'tsp', item: 'mustard seeds' },
      { qty: 1, unit: 'sprig', item: 'curry leaves' },
      { qty: 2, unit: 'piece', item: 'cloves' },
      { qty: 1, unit: 'inch', item: 'cinnamon stick' },
      { qty: 1, unit: 'piece', item: 'dried red chilli' },
      { qty: 1, unit: 'pinch', item: 'asafoetida (hing)' },
      { qty: 2, unit: 'tbsp', item: 'coriander leaves', note: 'chopped' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'Drain the soaked moong dal and add it to a pressure cooker with the rice, turmeric, salt, 1 tsp ghee and 3 cups of water.',
      },
      {
        text: 'Pressure-cook on medium heat for 3 whistles (about 12 minutes), then let the pressure release naturally so the khichdi turns soft and porridge-like.',
        timerMin: 12,
      },
      {
        text: 'Meanwhile, whisk the curd and besan together until completely smooth with no lumps, then whisk in 2 cups of water, the jaggery, sonth and salt to make a thin kadhi base.',
      },
      {
        text: 'Pour the kadhi base into a pan with the slit green chilli and bring it to a boil over medium heat, stirring constantly so the curd does not split.',
        timerMin: 5,
      },
      {
        text: 'Once it boils, lower the heat and simmer, stirring every minute, until it thickens slightly and loses the raw besan smell.',
        timerMin: 8,
      },
      {
        text: 'For the tempering, heat the remaining ghee in a small pan, add mustard seeds and let them crackle, then add cumin, cloves, cinnamon, red chilli, curry leaves and asafoetida and fry for 20 seconds.',
      },
      {
        text: 'Pour most of the tempering into the kadhi and the rest over the khichdi, mash the khichdi lightly with a ladle and add hot water if it has become too thick.',
      },
      {
        text: 'Garnish the kadhi with coriander and serve hot, pouring the kadhi generously over the khichdi.',
      },
    ],
    nutrition: { kcal: 400, proteinG: 13, carbsG: 58, fatG: 13, fibreG: 4 },
  },
  {
    id: 'maharashtrian-misal-pav',
    name: 'Maharashtrian Misal Pav',
    cuisine: 'Maharashtrian',
    dietMode: 'vegan',
    description:
      'Fiery Kolhapuri-style sprouted matki curry under a red oil-slicked tarri, topped with crunchy farsan and onion and mopped up with soft pav.',
    servings: 4,
    prepMinutes: 20,
    cookMinutes: 35,
    difficulty: 'medium',
    spice: 'fiery',
    protein: 'high',
    costBand: '₹',
    tags: ['High protein', 'Regional', 'Weekend', 'Breakfast'],
    ingredients: [
      { qty: 2, unit: 'cup', item: 'sprouted matki (moth beans)', note: 'sprouted over 1–2 days' },
      { qty: 2, unit: 'piece', item: 'onions (medium)', note: '1 thinly sliced, 1 finely chopped for topping' },
      { qty: 2, unit: 'piece', item: 'tomatoes', note: 'finely chopped' },
      { qty: 0.25, unit: 'cup', item: 'dry grated coconut (kopra)' },
      { qty: 1, unit: 'inch', item: 'ginger' },
      { qty: 6, unit: 'clove', item: 'garlic' },
      { qty: 2, unit: 'tbsp', item: 'misal masala or goda masala' },
      { qty: 1.5, unit: 'tsp', item: 'Kashmiri red chilli powder' },
      { qty: 0.5, unit: 'tsp', item: 'turmeric powder' },
      { qty: 1, unit: 'tsp', item: 'mustard seeds' },
      { qty: 1, unit: 'tsp', item: 'cumin seeds' },
      { qty: 0.25, unit: 'tsp', item: 'asafoetida (hing)' },
      { qty: 1, unit: 'sprig', item: 'curry leaves' },
      { qty: 4, unit: 'tbsp', item: 'groundnut oil' },
      { qty: 1, unit: 'cup', item: 'farsan (spicy sev-chivda mix)' },
      { qty: 8, unit: 'piece', item: 'pav bread rolls', note: 'check the label or ask the bakery that the pav is egg- and dairy-free' },
      { qty: 1, unit: 'piece', item: 'lemon', note: 'cut into wedges' },
      { qty: 3, unit: 'tbsp', item: 'coriander leaves', note: 'chopped' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'Pressure-cook the sprouted matki with turmeric, salt and 2 cups of water for 1 whistle on medium heat, then release pressure; the sprouts should be tender but still whole.',
        timerMin: 6,
      },
      {
        text: 'In a dry pan on medium-low, roast the sliced onion until browned at the edges, add the dry coconut and roast until it turns golden and smells nutty, then cool.',
        timerMin: 8,
      },
      {
        text: 'Grind the roasted onion and coconut with ginger, garlic and a splash of water into a smooth, thick paste.',
      },
      {
        text: 'Heat the oil in a deep pan, crackle the mustard seeds, then add cumin, asafoetida and curry leaves; stir in the ground paste and fry on medium heat until it darkens and oil starts to separate at the edges.',
        timerMin: 6,
      },
      {
        text: 'Add the tomatoes, chilli powder and misal masala and cook, stirring, until the tomatoes collapse completely and a red oil layer rises to the top.',
        timerMin: 6,
      },
      {
        text: 'Add the cooked matki with its liquid plus 2–3 cups of hot water to make a thin, soupy curry, check salt and simmer uncovered so the red oil (tarri) floats on top.',
        timerMin: 12,
      },
      {
        text: 'Warm the pav on a hot tawa for 30 seconds a side, pressing lightly, until toasty.',
      },
      {
        text: 'To serve, ladle the misal into bowls, spoon extra tarri over it, and top with plenty of farsan, chopped onion and coriander; serve immediately with pav and a lemon wedge so the farsan stays crunchy.',
      },
    ],
    nutrition: { kcal: 560, proteinG: 18, carbsG: 76, fatG: 21, fibreG: 12 },
  },
  {
    id: 'maharashtrian-varan-bhaat',
    name: 'Maharashtrian Varan Bhaat',
    cuisine: 'Maharashtrian',
    dietMode: 'vegetarian',
    description:
      'The Maharashtrian comfort plate: plain turmeric toor dal with a hint of jaggery, poured over hot rice with a spoon of ghee and a squeeze of lime.',
    servings: 3,
    prepMinutes: 5,
    cookMinutes: 25,
    difficulty: 'easy',
    spice: 'mild',
    protein: 'medium',
    costBand: '₹',
    tags: ['Quick', 'Regional', 'Budget', 'Kid-friendly'],
    ingredients: [
      { qty: 0.5, unit: 'cup', item: 'toor dal', note: 'rinsed' },
      { qty: 1, unit: 'cup', item: 'rice (ambemohar or sona masuri)', note: 'rinsed' },
      { qty: 0.5, unit: 'tsp', item: 'turmeric powder' },
      { qty: 0.25, unit: 'tsp', item: 'asafoetida (hing)' },
      { qty: 1, unit: 'tsp', item: 'jaggery', note: 'grated' },
      { qty: 2, unit: 'tbsp', item: 'ghee', note: 'plus extra to serve' },
      { qty: 0.5, unit: 'tsp', item: 'mustard seeds' },
      { qty: 0.5, unit: 'tsp', item: 'cumin seeds' },
      { qty: 1, unit: 'sprig', item: 'curry leaves' },
      { qty: 1, unit: 'piece', item: 'lime', note: 'cut into wedges' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'Put the toor dal in the pressure cooker with 1.5 cups water, turmeric and a drop of ghee; place the rice with 2 cups water in a separate container on top (pot-in-pot).',
      },
      {
        text: 'Pressure-cook on medium heat for 4 whistles (about 15 minutes), then let the pressure release naturally.',
        timerMin: 15,
      },
      {
        text: 'Whisk the cooked dal with a ladle until completely smooth and mushy, adding about half a cup of hot water to reach a pourable consistency.',
      },
      {
        text: 'Heat 1 tbsp ghee in a small pan, crackle the mustard seeds, then add cumin, curry leaves and asafoetida and fry for 15 seconds without letting them burn.',
      },
      {
        text: 'Pour the tempering into the dal, add salt and the jaggery, and simmer on low, stirring, until it just comes to a gentle boil.',
        timerMin: 5,
      },
      {
        text: 'Serve by mounding hot rice on the plate, pouring the varan over it, topping with a teaspoon of ghee and squeezing lime over just before eating.',
      },
    ],
    nutrition: { kcal: 420, proteinG: 12, carbsG: 68, fatG: 11, fibreG: 5 },
  },
  {
    id: 'bengali-shukto',
    name: 'Bengali Shukto',
    cuisine: 'Bengali',
    dietMode: 'vegan',
    description:
      'A gently bitter-sweet Bengali medley of bitter gourd, drumstick, raw banana and brinjal in a light mustard-ginger gravy, made vegan with coconut paste instead of dairy.',
    servings: 4,
    prepMinutes: 20,
    cookMinutes: 30,
    difficulty: 'medium',
    spice: 'mild',
    protein: 'low',
    costBand: '₹',
    tags: ['Regional', 'Weekend'],
    ingredients: [
      { qty: 1, unit: 'piece', item: 'bitter gourd (small)', note: 'thin rounds' },
      { qty: 1, unit: 'piece', item: 'raw banana', note: 'peeled, 2-inch batons' },
      { qty: 1, unit: 'piece', item: 'sweet potato (small)', note: 'peeled, 2-inch batons' },
      { qty: 1, unit: 'piece', item: 'brinjal (small)', note: '2-inch batons' },
      { qty: 2, unit: 'piece', item: 'drumsticks', note: 'cut into 3-inch pieces' },
      { qty: 100, unit: 'g', item: 'flat beans (sheem)', note: 'halved' },
      { qty: 1, unit: 'tbsp', item: 'yellow mustard seeds', note: 'soaked 10 minutes, for paste' },
      { qty: 1, unit: 'inch', item: 'ginger', note: 'ground to a paste' },
      { qty: 3, unit: 'tbsp', item: 'fresh grated coconut', note: 'ground to a smooth paste with 4 tbsp water' },
      { qty: 1, unit: 'tbsp', item: 'poppy seeds (posto)', note: 'soaked, optional' },
      { qty: 1, unit: 'tsp', item: 'panch phoron' },
      { qty: 1, unit: 'piece', item: 'bay leaf' },
      { qty: 1, unit: 'tsp', item: 'sugar' },
      { qty: 0.25, unit: 'tsp', item: 'turmeric powder' },
      { qty: 3, unit: 'tbsp', item: 'mustard oil' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'Grind the soaked mustard seeds (and poppy seeds, if using) with a pinch of salt and 2 tbsp water into a smooth paste; keep the ginger and coconut pastes ready.',
      },
      {
        text: 'Heat the mustard oil in a kadai until it just smokes, then lower the heat and fry the bitter gourd rounds with a pinch of salt and turmeric until crisp and golden; remove and set aside.',
        timerMin: 5,
      },
      {
        text: 'Lightly fry the brinjal batons in the same oil for 2 minutes until they colour at the edges, then remove.',
        timerMin: 2,
      },
      {
        text: 'Add the panch phoron and bay leaf to the oil and let them splutter, then add the raw banana, sweet potato, drumsticks and beans and toss on medium heat for 3–4 minutes.',
        timerMin: 4,
      },
      {
        text: 'Stir in the ginger and mustard pastes with 1.5 cups water, salt and sugar, cover and simmer until the vegetables are just tender but hold their shape.',
        timerMin: 12,
      },
      {
        text: 'Return the brinjal and half the fried bitter gourd, stir in the coconut paste and simmer uncovered on low for 3–4 minutes until the gravy turns lightly creamy.',
        timerMin: 4,
      },
      {
        text: 'Check salt and sugar (it should taste mildly bitter, then sweet), top with the remaining bitter gourd, and serve as the first course with plain rice.',
      },
    ],
    nutrition: { kcal: 210, proteinG: 4, carbsG: 24, fatG: 12, fibreG: 7 },
  },
  {
    id: 'bengali-cholar-dal',
    name: 'Bengali Cholar Dal',
    cuisine: 'Bengali',
    dietMode: 'vegetarian',
    description:
      'Festive, gently sweet Bengali chana dal with ghee-fried coconut slivers, raisins and whole garam masala — the classic partner for luchi.',
    servings: 3,
    prepMinutes: 10,
    cookMinutes: 30,
    difficulty: 'easy',
    spice: 'mild',
    protein: 'high',
    costBand: '₹',
    tags: ['High protein', 'Regional', 'Weekend'],
    ingredients: [
      { qty: 1, unit: 'cup', item: 'chana dal', note: 'rinsed, soaked 2 hours' },
      { qty: 0.5, unit: 'tsp', item: 'turmeric powder' },
      { qty: 0.25, unit: 'cup', item: 'fresh coconut', note: 'cut into small thin slivers' },
      { qty: 1, unit: 'tbsp', item: 'raisins' },
      { qty: 2, unit: 'tbsp', item: 'ghee' },
      { qty: 1, unit: 'tsp', item: 'cumin seeds' },
      { qty: 2, unit: 'piece', item: 'bay leaves' },
      { qty: 1, unit: 'inch', item: 'cinnamon stick' },
      { qty: 3, unit: 'piece', item: 'green cardamom', note: 'lightly crushed' },
      { qty: 3, unit: 'piece', item: 'cloves' },
      { qty: 2, unit: 'piece', item: 'dried red chillies' },
      { qty: 1, unit: 'tsp', item: 'ginger paste' },
      { qty: 1, unit: 'tsp', item: 'cumin powder' },
      { qty: 2, unit: 'tsp', item: 'sugar' },
      { qty: 0.5, unit: 'tsp', item: 'garam masala powder' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'Soak the chana dal in plenty of water for 2 hours, then drain.',
        timerMin: 120,
      },
      {
        text: 'Pressure-cook the dal with 2.5 cups water, turmeric and salt for 2 whistles on medium heat (about 10 minutes); the grains should be soft but still hold their shape, not mushy.',
        timerMin: 10,
      },
      {
        text: 'Heat the ghee in a kadai on medium and fry the coconut slivers until golden, then add the raisins for a few seconds until they puff; scoop both out and set aside.',
        timerMin: 3,
      },
      {
        text: 'In the same ghee, add cumin seeds, bay leaves, cinnamon, cardamom, cloves and dried red chillies and fry for 30 seconds until fragrant.',
      },
      {
        text: 'Add the ginger paste and cumin powder with a splash of water and sauté for a minute until the raw smell goes.',
      },
      {
        text: 'Pour in the cooked dal with its water, add the sugar and half the coconut and raisins, and simmer uncovered, stirring now and then, until it thickens to a spoon-coating consistency.',
        timerMin: 10,
      },
      {
        text: 'Finish with garam masala and the remaining coconut and raisins, rest for 2 minutes and serve with luchi, puri or rice.',
      },
    ],
    nutrition: { kcal: 380, proteinG: 15, carbsG: 50, fatG: 14, fibreG: 12 },
  },
  {
    id: 'continental-mediterranean-bowl',
    name: 'Mediterranean Chickpea Quinoa Bowl',
    cuisine: 'Continental',
    dietMode: 'vegan',
    description:
      'A bright, filling bowl of fluffy quinoa, lemony chickpeas and crunchy salad under a garlicky tahini dressing.',
    servings: 2,
    prepMinutes: 15,
    cookMinutes: 15,
    difficulty: 'easy',
    spice: 'mild',
    protein: 'high',
    costBand: '₹₹',
    tags: ['Quick', 'High protein', 'Tiffin box'],
    ingredients: [
      { qty: 0.5, unit: 'cup', item: 'quinoa', note: 'rinsed well' },
      { qty: 1.5, unit: 'cup', item: 'boiled chickpeas', note: 'drained' },
      { qty: 1, unit: 'piece', item: 'cucumber', note: 'diced' },
      { qty: 10, unit: 'piece', item: 'cherry tomatoes', note: 'halved' },
      { qty: 0.5, unit: 'piece', item: 'red onion', note: 'finely sliced' },
      { qty: 8, unit: 'piece', item: 'black olives', note: 'sliced, optional' },
      { qty: 3, unit: 'tbsp', item: 'tahini' },
      { qty: 1, unit: 'piece', item: 'lemon', note: 'juiced' },
      { qty: 1, unit: 'clove', item: 'garlic', note: 'grated' },
      { qty: 2, unit: 'tbsp', item: 'extra-virgin olive oil' },
      { qty: 0.5, unit: 'tsp', item: 'smoked paprika' },
      { qty: 0.5, unit: 'tsp', item: 'dried oregano' },
      { qty: 1, unit: 'handful', item: 'fresh parsley or coriander', note: 'chopped' },
      { qty: null, unit: 'to taste', item: 'salt and black pepper' },
    ],
    steps: [
      {
        text: 'Add the rinsed quinoa to a saucepan with 1 cup water and a pinch of salt, bring to a boil, then cover and simmer on low until all the water is absorbed.',
        timerMin: 12,
      },
      {
        text: 'Take the quinoa off the heat, keep it covered for 5 minutes, then fluff with a fork and spread on a plate to cool slightly.',
        timerMin: 5,
      },
      {
        text: 'Warm 1 tbsp olive oil in a pan on medium, add the chickpeas with paprika, oregano and a pinch of salt and toss for 3–4 minutes until they are hot and lightly crisp at the edges.',
        timerMin: 4,
      },
      {
        text: 'Whisk the tahini with the garlic, half the lemon juice, a pinch of salt and 3–4 tbsp cold water until smooth and pourable; it will thicken first, then loosen.',
      },
      {
        text: 'Toss the cucumber, tomatoes, onion and olives with the remaining olive oil, remaining lemon juice, salt and pepper.',
      },
      {
        text: 'Divide the quinoa between two bowls, top with the salad and warm chickpeas, drizzle generously with the tahini dressing and finish with chopped parsley.',
      },
    ],
    nutrition: { kcal: 610, proteinG: 21, carbsG: 66, fatG: 30, fibreG: 15 },
  },
  {
    id: 'continental-mushroom-risotto',
    name: 'Mushroom Risotto',
    cuisine: 'Continental',
    dietMode: 'vegetarian',
    description:
      'Creamy, slowly stirred risotto with deeply browned mushrooms, finished with butter and a rennet-free hard cheese.',
    servings: 3,
    prepMinutes: 15,
    cookMinutes: 35,
    difficulty: 'medium',
    spice: 'mild',
    protein: 'medium',
    costBand: '₹₹₹',
    tags: ['Weekend'],
    ingredients: [
      { qty: 1, unit: 'cup', item: 'arborio rice', note: 'do not rinse' },
      { qty: 250, unit: 'g', item: 'button or cremini mushrooms', note: 'sliced' },
      { qty: 1, unit: 'l', item: 'vegetable stock', note: 'kept hot on a back burner' },
      { qty: 1, unit: 'piece', item: 'onion (medium)', note: 'finely chopped' },
      { qty: 3, unit: 'clove', item: 'garlic', note: 'minced' },
      { qty: 2, unit: 'tbsp', item: 'olive oil' },
      { qty: 2, unit: 'tbsp', item: 'butter', note: 'divided' },
      { qty: 40, unit: 'g', item: 'vegetarian hard cheese (rennet-free)', note: 'finely grated' },
      { qty: 1, unit: 'tsp', item: 'dried thyme' },
      { qty: 1, unit: 'tbsp', item: 'lemon juice' },
      { qty: 2, unit: 'tbsp', item: 'parsley', note: 'chopped' },
      { qty: null, unit: 'to taste', item: 'salt and black pepper' },
    ],
    steps: [
      {
        text: 'Heat 1 tbsp olive oil and 1 tsp butter in a wide pan over high heat, add the mushrooms in a single layer with the thyme and leave them undisturbed for 2 minutes, then stir and cook until deep golden and any water has evaporated; season and set aside.',
        timerMin: 7,
      },
      {
        text: 'Lower the heat to medium, add the remaining olive oil and the onion and cook until soft and translucent but not browned, then add the garlic for 30 seconds.',
        timerMin: 5,
      },
      {
        text: 'Add the rice and stir for 1–2 minutes until the grains are coated in oil and the edges look translucent.',
        timerMin: 2,
      },
      {
        text: 'Add one ladle of hot stock and stir often until it is almost fully absorbed, then add the next ladle; keep going on a steady medium simmer.',
      },
      {
        text: 'Continue adding stock a ladle at a time for about 18–20 minutes, until the rice is creamy outside and just tender with a slight bite in the centre.',
        timerMin: 20,
      },
      {
        text: 'Stir in two-thirds of the mushrooms, then take the pan off the heat and beat in the remaining butter, the grated cheese and lemon juice with a final splash of stock so it flows like lava.',
      },
      {
        text: 'Cover and rest for 2 minutes, check salt and pepper, and serve immediately topped with the remaining mushrooms and parsley.',
        timerMin: 2,
      },
    ],
    nutrition: { kcal: 470, proteinG: 12, carbsG: 62, fatG: 19, fibreG: 3 },
  },
  {
    id: 'tamil-jain-poricha-kootu',
    name: 'Tamil Poricha Kootu (Jain-friendly)',
    cuisine: 'Tamil',
    dietMode: 'vegan',
    description:
      'A mild, comforting Tamil kootu of chow-chow and beans simmered with moong dal and a pepper-cumin coconut paste, with no onion, garlic or root vegetables.',
    servings: 3,
    prepMinutes: 10,
    cookMinutes: 25,
    difficulty: 'easy',
    spice: 'mild',
    protein: 'medium',
    costBand: '₹',
    tags: ['Jain-friendly', 'Regional', 'Budget', 'Kid-friendly'],
    ingredients: [
      { qty: 0.5, unit: 'cup', item: 'split yellow moong dal', note: 'rinsed' },
      { qty: 1, unit: 'piece', item: 'chow-chow (chayote), medium', note: 'peeled, seed removed, 1-cm cubes' },
      { qty: 100, unit: 'g', item: 'green beans', note: 'cut into 1-cm pieces' },
      { qty: 0.25, unit: 'tsp', item: 'turmeric powder' },
      { qty: 0.33, unit: 'cup', item: 'fresh grated coconut' },
      { qty: 1, unit: 'tsp', item: 'cumin seeds', note: 'for the paste' },
      { qty: 0.5, unit: 'tsp', item: 'black peppercorns' },
      { qty: 1, unit: 'tsp', item: 'urad dal', note: 'for the paste' },
      { qty: 1, unit: 'piece', item: 'dried red chilli', note: 'for the paste' },
      { qty: 1, unit: 'tbsp', item: 'coconut oil' },
      { qty: 1, unit: 'tsp', item: 'mustard seeds' },
      { qty: 1, unit: 'tsp', item: 'urad dal', note: 'for tempering' },
      { qty: 1, unit: 'sprig', item: 'curry leaves' },
      { qty: 1, unit: 'pinch', item: 'asafoetida (hing)' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'Pressure-cook the moong dal with 1.5 cups water and the turmeric for 3 whistles (about 10 minutes) on medium heat, then mash lightly.',
        timerMin: 10,
      },
      {
        text: 'Meanwhile, in a few drops of coconut oil, roast the urad dal, pepper, cumin and red chilli on low heat until the dal turns golden, then grind with the coconut and a little water into a coarse paste.',
        timerMin: 4,
      },
      {
        text: 'Cook the chow-chow and beans in a pan with 1 cup water and salt, covered, on medium heat until tender but not mushy.',
        timerMin: 10,
      },
      {
        text: 'Add the mashed dal and the coconut paste to the vegetables, stir well and simmer for 4–5 minutes until it thickens to a soft, spoonable consistency; loosen with hot water if needed.',
        timerMin: 5,
      },
      {
        text: 'Heat the coconut oil in a small pan, crackle the mustard seeds, then add urad dal, curry leaves and asafoetida and fry until the dal turns golden.',
      },
      {
        text: 'Pour the tempering over the kootu, check salt and serve warm with rice and a spoon of oil, or alongside rasam and rice.',
      },
    ],
    nutrition: { kcal: 250, proteinG: 10, carbsG: 27, fatG: 11, fibreG: 7 },
  },
  {
    id: 'north-indian-chana-masala',
    name: 'North Indian Chana Masala',
    cuisine: 'North Indian',
    dietMode: 'vegan',
    description:
      'Dhaba-style chickpeas simmered in a dark, tangy onion-tomato masala, darkened with tea and sharpened with amchur and fresh ginger.',
    servings: 3,
    prepMinutes: 15,
    cookMinutes: 40,
    difficulty: 'medium',
    spice: 'medium',
    protein: 'high',
    costBand: '₹',
    tags: ['High protein', 'Budget', 'Tiffin box'],
    ingredients: [
      { qty: 1.25, unit: 'cup', item: 'dried kabuli chickpeas', note: 'soaked overnight (8 hours)' },
      { qty: 1, unit: 'piece', item: 'black tea bag', note: 'for colour' },
      { qty: 2, unit: 'piece', item: 'onions (medium)', note: 'finely chopped' },
      { qty: 3, unit: 'piece', item: 'tomatoes (medium)', note: 'pureed' },
      { qty: 1, unit: 'tbsp', item: 'ginger-garlic paste' },
      { qty: 2, unit: 'piece', item: 'green chillies', note: 'slit' },
      { qty: 2, unit: 'tbsp', item: 'chana masala powder' },
      { qty: 1, unit: 'tsp', item: 'Kashmiri red chilli powder' },
      { qty: 1, unit: 'tsp', item: 'coriander powder' },
      { qty: 0.5, unit: 'tsp', item: 'turmeric powder' },
      { qty: 1, unit: 'tsp', item: 'amchur (dry mango powder)' },
      { qty: 1, unit: 'tsp', item: 'cumin seeds' },
      { qty: 1, unit: 'piece', item: 'bay leaf' },
      { qty: 3, unit: 'tbsp', item: 'oil' },
      { qty: 1, unit: 'inch', item: 'ginger', note: 'julienned, for garnish' },
      { qty: 3, unit: 'tbsp', item: 'coriander leaves', note: 'chopped' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'Soak the chickpeas overnight in plenty of water; they should roughly double in size. Drain and rinse.',
        timerMin: 480,
      },
      {
        text: 'Pressure-cook the chickpeas with 3 cups water, salt and the tea bag on high until the first whistle, then on low for 15 minutes (about 5–6 whistles total); they should crush easily between your fingers. Discard the tea bag and keep the dark cooking liquid.',
        timerMin: 20,
      },
      {
        text: 'Heat the oil in a kadai on medium, add cumin and bay leaf, then the onions, and fry, stirring, until deep golden brown.',
        timerMin: 10,
      },
      {
        text: 'Add the ginger-garlic paste and green chillies and fry for a minute until the raw smell goes.',
      },
      {
        text: 'Add the tomato puree, turmeric, chilli powder, coriander powder and chana masala, and cook on medium, stirring often, until the masala thickens and oil separates at the sides.',
        timerMin: 8,
      },
      {
        text: 'Add the chickpeas with about 1 cup of their cooking liquid, mash a few chickpeas against the side of the pan to thicken the gravy, and simmer uncovered on low.',
        timerMin: 12,
      },
      {
        text: 'Stir in the amchur, check salt and tang, then finish with ginger juliennes and coriander; serve with bhature, kulcha, roti or rice.',
      },
    ],
    nutrition: { kcal: 420, proteinG: 16, carbsG: 58, fatG: 15, fibreG: 15 },
  },
  {
    id: 'kerala-puttu-kadala',
    name: 'Kerala Puttu with Kadala Curry',
    cuisine: 'Kerala',
    dietMode: 'vegan',
    description:
      'Steamed cylinders of rice flour and coconut served with a roasted-coconut black chickpea curry — Kerala’s favourite breakfast.',
    servings: 3,
    prepMinutes: 25,
    cookMinutes: 45,
    difficulty: 'medium',
    spice: 'medium',
    protein: 'medium',
    costBand: '₹',
    tags: ['Regional', 'Breakfast', 'Weekend'],
    ingredients: [
      { qty: 1, unit: 'cup', item: 'kala chana (black chickpeas)', note: 'soaked overnight (8 hours)' },
      { qty: 2, unit: 'cup', item: 'roasted puttu podi (rice flour)' },
      { qty: 1, unit: 'cup', item: 'fresh grated coconut', note: 'for layering the puttu' },
      { qty: 0.75, unit: 'cup', item: 'water', note: 'lukewarm, salted, for the puttu flour' },
      { qty: 0.5, unit: 'cup', item: 'fresh grated coconut', note: 'for the curry masala' },
      { qty: 10, unit: 'piece', item: 'shallots (small onions)', note: 'sliced' },
      { qty: 1, unit: 'inch', item: 'ginger', note: 'chopped' },
      { qty: 3, unit: 'clove', item: 'garlic', note: 'chopped' },
      { qty: 1, unit: 'piece', item: 'tomato', note: 'chopped' },
      { qty: 2, unit: 'tsp', item: 'coriander powder' },
      { qty: 1, unit: 'tsp', item: 'Kashmiri red chilli powder' },
      { qty: 0.25, unit: 'tsp', item: 'turmeric powder' },
      { qty: 1, unit: 'tsp', item: 'garam masala powder' },
      { qty: 1, unit: 'tsp', item: 'mustard seeds' },
      { qty: 2, unit: 'sprig', item: 'curry leaves' },
      { qty: 2, unit: 'piece', item: 'dried red chillies' },
      { qty: 3, unit: 'tbsp', item: 'coconut oil' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'Soak the kala chana overnight in plenty of water, then drain.',
        timerMin: 480,
      },
      {
        text: 'Pressure-cook the chana with 3 cups water, turmeric and salt for 6–7 whistles on medium heat (about 25 minutes) until soft all the way through.',
        timerMin: 25,
      },
      {
        text: 'Meanwhile, dry-roast half a cup of coconut in a pan on low heat, stirring constantly, until evenly dark brown; add the coriander powder, chilli powder and garam masala for 30 seconds, cool and grind to a fine paste with a little water.',
        timerMin: 8,
      },
      {
        text: 'Heat 2 tbsp coconut oil, crackle the mustard seeds, add half the curry leaves and sauté the shallots, ginger and garlic until golden, then the tomato until soft.',
        timerMin: 7,
      },
      {
        text: 'Add the cooked chana with its liquid and the roasted-coconut paste and simmer on low until the gravy is thick and dark brown, mashing a few chana to thicken it.',
        timerMin: 10,
      },
      {
        text: 'For the puttu, sprinkle the salted water over the rice flour a little at a time and rub with your fingertips until it feels like damp sand that holds a shape when pressed; break up any lumps.',
      },
      {
        text: 'Fill the puttu maker in layers — a spoon of coconut, then a few spoons of flour, repeating to the top and ending with coconut — and steam over vigorously boiling water until steam escapes steadily from the top lid.',
        timerMin: 8,
      },
      {
        text: 'Temper the curry with the remaining coconut oil, dried red chillies and curry leaves, then push the puttu out with the rod and serve hot with the kadala curry.',
      },
    ],
    nutrition: { kcal: 610, proteinG: 17, carbsG: 88, fatG: 22, fibreG: 16 },
  },
  {
    id: 'tofu-bhurji',
    name: 'Tofu Bhurji',
    cuisine: 'North Indian',
    dietMode: 'vegan',
    description:
      'A quick, protein-packed scramble of crumbled firm tofu with onion, tomato, green chilli and a pinch of kala namak for that classic bhurji taste.',
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 15,
    difficulty: 'easy',
    spice: 'medium',
    protein: 'high',
    costBand: '₹₹',
    tags: ['Quick', 'High protein', 'Breakfast', 'Tiffin box'],
    ingredients: [
      { qty: 300, unit: 'g', item: 'firm tofu', note: 'pressed 10 minutes, crumbled by hand' },
      { qty: 1, unit: 'piece', item: 'onion (medium)', note: 'finely chopped' },
      { qty: 1, unit: 'piece', item: 'tomato (medium)', note: 'finely chopped' },
      { qty: 0.25, unit: 'cup', item: 'capsicum', note: 'finely chopped, optional' },
      { qty: 1, unit: 'piece', item: 'green chilli', note: 'finely chopped' },
      { qty: 1, unit: 'tsp', item: 'ginger', note: 'grated' },
      { qty: 1, unit: 'tsp', item: 'cumin seeds' },
      { qty: 0.5, unit: 'tsp', item: 'turmeric powder' },
      { qty: 0.5, unit: 'tsp', item: 'red chilli powder' },
      { qty: 0.5, unit: 'tsp', item: 'garam masala powder' },
      { qty: 0.25, unit: 'tsp', item: 'kala namak (black salt)' },
      { qty: 1.5, unit: 'tbsp', item: 'oil' },
      { qty: 2, unit: 'tbsp', item: 'coriander leaves', note: 'chopped' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'Wrap the tofu in a clean kitchen towel and press it under a heavy pan to squeeze out water, then crumble it with your fingers into small, uneven pieces.',
        timerMin: 10,
      },
      {
        text: 'Heat the oil in a pan on medium, add the cumin seeds and let them sizzle, then add the onion and cook until soft and light golden.',
        timerMin: 4,
      },
      {
        text: 'Add the ginger, green chilli and capsicum and sauté for a minute, then add the tomato with a pinch of salt and cook until it turns soft and pulpy.',
        timerMin: 4,
      },
      {
        text: 'Stir in the turmeric and red chilli powder for 20 seconds, then add the crumbled tofu and toss well so every piece turns yellow.',
      },
      {
        text: 'Cook on medium-high, stirring occasionally, until the tofu is hot and any water has cooked off, leaving it slightly dry and fluffy.',
        timerMin: 5,
      },
      {
        text: 'Sprinkle over the garam masala, kala namak and coriander, toss once more and serve hot with toasted bread, roti or rolled in a paratha.',
      },
    ],
    nutrition: { kcal: 330, proteinG: 24, carbsG: 12, fatG: 21, fibreG: 4 },
  },
  {
    id: 'lemon-rice',
    name: 'Tamil Lemon Rice (Elumichai Sadam)',
    cuisine: 'Tamil',
    dietMode: 'vegan',
    description:
      'Bright yellow tempered rice with crunchy peanuts, chana dal and curry leaves, sharpened with fresh lemon — the classic tiffin and travel rice.',
    servings: 3,
    prepMinutes: 5,
    cookMinutes: 15,
    difficulty: 'easy',
    spice: 'mild',
    protein: 'low',
    costBand: '₹',
    tags: ['Quick', 'Regional', 'Budget', 'Tiffin box', 'Kid-friendly'],
    ingredients: [
      { qty: 3, unit: 'cup', item: 'cooked rice (ponni or sona masuri)', note: 'cooked grainy and cooled, from about 1 cup raw' },
      { qty: 1.5, unit: 'piece', item: 'lemons', note: 'juiced (about 3 tbsp)' },
      { qty: 2, unit: 'tbsp', item: 'gingelly (sesame) oil' },
      { qty: 3, unit: 'tbsp', item: 'raw peanuts' },
      { qty: 1, unit: 'tsp', item: 'mustard seeds' },
      { qty: 1, unit: 'tsp', item: 'urad dal' },
      { qty: 1, unit: 'tbsp', item: 'chana dal' },
      { qty: 2, unit: 'piece', item: 'dried red chillies', note: 'broken' },
      { qty: 2, unit: 'piece', item: 'green chillies', note: 'slit' },
      { qty: 1, unit: 'inch', item: 'ginger', note: 'finely chopped' },
      { qty: 2, unit: 'sprig', item: 'curry leaves' },
      { qty: 0.5, unit: 'tsp', item: 'turmeric powder' },
      { qty: 0.25, unit: 'tsp', item: 'asafoetida (hing)' },
      { qty: 2, unit: 'tbsp', item: 'coriander leaves', note: 'chopped' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'Spread the cooked rice on a wide plate to cool so the grains stay separate; freshly hot rice turns mushy when mixed.',
      },
      {
        text: 'Heat the gingelly oil in a kadai on medium, add the peanuts and fry, stirring, until they crackle and turn golden brown.',
        timerMin: 3,
      },
      {
        text: 'Add the mustard seeds and let them splutter, then add the urad dal and chana dal and fry until both turn golden.',
        timerMin: 2,
      },
      {
        text: 'Add the red chillies, green chillies, ginger, curry leaves and asafoetida and sauté for 30 seconds, then turn off the heat and stir in the turmeric so it does not burn.',
      },
      {
        text: 'Add the salt and lemon juice to the tempering (with the heat off, so the lemon does not turn bitter) and stir to make a loose yellow sauce.',
      },
      {
        text: 'Add the rice and fold gently with a flat spoon until every grain is evenly yellow, taste for salt and lemon, then rest for 10 minutes so the flavours soak in before serving with coriander.',
        timerMin: 10,
      },
    ],
    nutrition: { kcal: 380, proteinG: 8, carbsG: 58, fatG: 13, fibreG: 3 },
  },
  {
    id: 'tamil-veg-kurma',
    name: 'Tamil Vegetable Kurma',
    cuisine: 'Tamil',
    dietMode: 'vegan',
    description:
      'A fragrant hotel-style kurma of mixed vegetables in a smooth coconut, cashew and fennel gravy, made for parotta, chapati and idiyappam.',
    servings: 4,
    prepMinutes: 20,
    cookMinutes: 25,
    difficulty: 'medium',
    spice: 'medium',
    protein: 'low',
    costBand: '₹₹',
    tags: ['Regional', 'Tiffin box'],
    ingredients: [
      { qty: 1, unit: 'piece', item: 'potato (medium)', note: 'peeled, 1-cm cubes' },
      { qty: 1, unit: 'piece', item: 'carrot', note: '1-cm cubes' },
      { qty: 100, unit: 'g', item: 'green beans', note: '1-inch pieces' },
      { qty: 0.5, unit: 'cup', item: 'green peas', note: 'fresh or frozen' },
      { qty: 1, unit: 'piece', item: 'onion (large)', note: 'thinly sliced' },
      { qty: 1, unit: 'piece', item: 'tomato', note: 'chopped' },
      { qty: 1, unit: 'tsp', item: 'ginger-garlic paste' },
      { qty: 0.5, unit: 'cup', item: 'fresh grated coconut', note: 'for the paste' },
      { qty: 8, unit: 'piece', item: 'cashews', note: 'soaked 10 minutes, for the paste' },
      { qty: 1, unit: 'tbsp', item: 'roasted gram (pottukadalai)', note: 'for the paste' },
      { qty: 3, unit: 'piece', item: 'green chillies', note: 'for the paste' },
      { qty: 1, unit: 'tsp', item: 'fennel seeds', note: 'for the paste' },
      { qty: 1, unit: 'tsp', item: 'coriander powder' },
      { qty: 0.25, unit: 'tsp', item: 'turmeric powder' },
      { qty: 1, unit: 'inch', item: 'cinnamon stick' },
      { qty: 2, unit: 'piece', item: 'cloves' },
      { qty: 2, unit: 'piece', item: 'green cardamom' },
      { qty: 1, unit: 'piece', item: 'bay leaf' },
      { qty: 1, unit: 'sprig', item: 'curry leaves' },
      { qty: 2, unit: 'tbsp', item: 'oil' },
      { qty: 2, unit: 'tbsp', item: 'coriander leaves', note: 'chopped' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'Grind the coconut, soaked cashews, roasted gram, green chillies and fennel seeds with about half a cup of water into a very smooth paste.',
      },
      {
        text: 'Heat the oil in a pan on medium, add the cinnamon, cloves, cardamom and bay leaf and let them sizzle for 20 seconds, then add the curry leaves and onion and fry until soft and light golden.',
        timerMin: 5,
      },
      {
        text: 'Add the ginger-garlic paste and sauté for a minute until the raw smell goes, then add the tomato and cook until it turns mushy.',
        timerMin: 4,
      },
      {
        text: 'Stir in the turmeric and coriander powder, then add the potato, carrot, beans and peas with salt and 1.5 cups water; cover and simmer until the vegetables are tender.',
        timerMin: 10,
      },
      {
        text: 'Pour in the ground coconut paste with half a cup of water, stir well and simmer on low, uncovered, stirring occasionally, until the kurma thickens and a thin sheen of oil appears on top — do not boil it hard or the coconut will split.',
        timerMin: 6,
      },
      {
        text: 'Check salt, add hot water if it is thicker than a pourable gravy, garnish with coriander and serve with parotta, chapati, idiyappam or appam.',
      },
    ],
    nutrition: { kcal: 260, proteinG: 6, carbsG: 24, fatG: 16, fibreG: 7 },
  },
  {
    id: 'chana-sundal',
    name: 'Chana Sundal',
    cuisine: 'Tamil',
    dietMode: 'vegan',
    description:
      'Temple-style boiled chickpeas tossed with mustard, curry leaves, green chilli and fresh coconut — a light, protein-rich evening snack.',
    servings: 4,
    prepMinutes: 5,
    cookMinutes: 25,
    difficulty: 'easy',
    spice: 'mild',
    protein: 'medium',
    costBand: '₹',
    tags: ['Regional', 'Budget', 'Tiffin box', 'Kid-friendly'],
    ingredients: [
      { qty: 1, unit: 'cup', item: 'dried kabuli chickpeas or kala chana', note: 'soaked overnight (8 hours)' },
      { qty: 1, unit: 'tbsp', item: 'coconut oil' },
      { qty: 1, unit: 'tsp', item: 'mustard seeds' },
      { qty: 1, unit: 'tsp', item: 'urad dal' },
      { qty: 2, unit: 'piece', item: 'dried red chillies', note: 'broken' },
      { qty: 1, unit: 'piece', item: 'green chilli', note: 'finely chopped' },
      { qty: 1, unit: 'tsp', item: 'ginger', note: 'finely chopped' },
      { qty: 1, unit: 'sprig', item: 'curry leaves' },
      { qty: 1, unit: 'pinch', item: 'asafoetida (hing)' },
      { qty: 0.25, unit: 'cup', item: 'fresh grated coconut' },
      { qty: 1, unit: 'tbsp', item: 'lemon juice', note: 'optional' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'Soak the chickpeas overnight in plenty of water, then drain and rinse.',
        timerMin: 480,
      },
      {
        text: 'Pressure-cook the chickpeas with 2.5 cups water and salt for 4–5 whistles on medium heat (about 18 minutes) until soft but still whole, then drain completely, saving the water for rasam or soup.',
        timerMin: 18,
      },
      {
        text: 'Heat the coconut oil in a kadai on medium, add the mustard seeds and let them splutter, then add the urad dal and fry until golden.',
        timerMin: 2,
      },
      {
        text: 'Add the red chillies, green chilli, ginger, curry leaves and asafoetida and sauté for 30 seconds until the curry leaves turn crisp.',
      },
      {
        text: 'Add the drained chickpeas with a pinch of salt and toss on medium heat for 2–3 minutes so they soak up the tempering and any moisture dries off.',
        timerMin: 3,
      },
      {
        text: 'Turn off the heat, add the grated coconut and lemon juice (if using), toss well and serve warm in small cups.',
      },
    ],
    nutrition: { kcal: 250, proteinG: 10, carbsG: 32, fatG: 9, fibreG: 9 },
  },
  {
    id: 'tomato-rasam',
    name: 'Tomato Rasam',
    cuisine: 'Tamil',
    dietMode: 'vegan',
    description:
      'A thin, tangy, peppery Tamil soup of ripe tomatoes, tamarind and freshly crushed pepper-cumin — soothing with rice or sipped hot on its own.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    difficulty: 'easy',
    spice: 'medium',
    protein: 'low',
    costBand: '₹',
    tags: ['Quick', 'Regional', 'Budget', 'One-pot'],
    ingredients: [
      { qty: 3, unit: 'piece', item: 'ripe tomatoes (medium)', note: 'chopped' },
      { qty: 1, unit: 'tbsp', item: 'tamarind', note: 'gooseberry-sized, soaked in half a cup of warm water' },
      { qty: 1, unit: 'tsp', item: 'black peppercorns' },
      { qty: 1, unit: 'tsp', item: 'cumin seeds' },
      { qty: 4, unit: 'clove', item: 'garlic', note: 'unpeeled' },
      { qty: 1, unit: 'tsp', item: 'rasam powder' },
      { qty: 0.25, unit: 'tsp', item: 'turmeric powder' },
      { qty: 0.25, unit: 'tsp', item: 'asafoetida (hing)' },
      { qty: 1, unit: 'tbsp', item: 'gingelly (sesame) oil' },
      { qty: 1, unit: 'tsp', item: 'mustard seeds' },
      { qty: 1, unit: 'piece', item: 'dried red chilli', note: 'broken' },
      { qty: 2, unit: 'sprig', item: 'curry leaves' },
      { qty: 3, unit: 'tbsp', item: 'coriander leaves and stems', note: 'chopped' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'Squeeze the soaked tamarind well and strain the juice, discarding the pulp and seeds.',
      },
      {
        text: 'Coarsely crush the pepper, cumin and garlic in a mortar or give them two short pulses in a mixer — you want a rough, fragrant crush, not a powder.',
      },
      {
        text: 'In a pot, combine the tamarind water, chopped tomatoes (squeezed with your hand to release juice), turmeric, rasam powder, half the curry leaves, salt and 2 cups of water.',
      },
      {
        text: 'Boil on medium heat until the raw tamarind smell disappears and the tomatoes are completely soft.',
        timerMin: 8,
      },
      {
        text: 'Add the crushed pepper-cumin-garlic and another 1.5 cups of water, and heat on low until a froth rises to the top; switch off just as it starts to bubble — never let rasam boil hard at this stage.',
        timerMin: 4,
      },
      {
        text: 'Heat the oil in a small pan, crackle the mustard seeds, add the red chilli, remaining curry leaves and asafoetida, and pour the tempering over the rasam.',
      },
      {
        text: 'Stir in the coriander, cover for 5 minutes to let the aroma settle in, and serve hot with rice or in cups as a soup.',
        timerMin: 5,
      },
    ],
    nutrition: { kcal: 70, proteinG: 2, carbsG: 9, fatG: 4, fibreG: 2 },
  },
  {
    id: 'moong-dal-chilla',
    name: 'Moong Dal Chilla',
    cuisine: 'North Indian',
    dietMode: 'vegan',
    description:
      'Crisp-edged savoury pancakes of soaked, ground yellow moong dal with ginger, chilli and onion — a high-protein breakfast ready in minutes once soaked.',
    servings: 3,
    prepMinutes: 15,
    cookMinutes: 20,
    difficulty: 'easy',
    spice: 'mild',
    protein: 'high',
    costBand: '₹',
    tags: ['High protein', 'Breakfast', 'Budget', 'Tiffin box'],
    ingredients: [
      { qty: 1, unit: 'cup', item: 'split yellow moong dal', note: 'soaked 3 hours' },
      { qty: 1, unit: 'inch', item: 'ginger' },
      { qty: 2, unit: 'piece', item: 'green chillies' },
      { qty: 0.5, unit: 'tsp', item: 'cumin seeds' },
      { qty: 0.25, unit: 'tsp', item: 'turmeric powder' },
      { qty: 1, unit: 'pinch', item: 'asafoetida (hing)' },
      { qty: 1, unit: 'piece', item: 'onion (small)', note: 'finely chopped' },
      { qty: 1, unit: 'piece', item: 'tomato (small)', note: 'deseeded, finely chopped' },
      { qty: 3, unit: 'tbsp', item: 'coriander leaves', note: 'chopped' },
      { qty: 2, unit: 'tbsp', item: 'oil', note: 'for cooking the chillas' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'Soak the moong dal in water for 3 hours, then drain completely.',
        timerMin: 180,
      },
      {
        text: 'Grind the dal with the ginger, green chillies, cumin and about a third of a cup of water into a smooth, thick batter that coats the back of a spoon, like dosa batter.',
      },
      {
        text: 'Stir in the turmeric, asafoetida, salt, onion, tomato and coriander; if the batter has thickened, add a spoon or two of water.',
      },
      {
        text: 'Heat a flat non-stick or cast-iron tawa on medium and grease it lightly; pour a ladle of batter in the centre and quickly spread it outwards in circles into a thin round.',
      },
      {
        text: 'Drizzle half a teaspoon of oil around the edges and cook until the underside is golden and the top looks dry and set.',
        timerMin: 2,
      },
      {
        text: 'Flip and cook the other side for about a minute until golden spots appear, pressing lightly with the spatula; repeat with the remaining batter, making about 6 chillas.',
        timerMin: 1,
      },
      {
        text: 'Serve hot with green chutney or tomato ketchup; they are best straight off the tawa while the edges are crisp.',
      },
    ],
    nutrition: { kcal: 320, proteinG: 17, carbsG: 42, fatG: 10, fibreG: 9 },
  },
  {
    id: 'kerala-cabbage-thoran',
    name: 'Kerala Cabbage Thoran',
    cuisine: 'Kerala',
    dietMode: 'vegan',
    description:
      'Finely shredded cabbage stir-fried in coconut oil with a crushed coconut, shallot and green chilli mix — a light, sweet Sadhya side ready in 20 minutes.',
    servings: 3,
    prepMinutes: 10,
    cookMinutes: 10,
    difficulty: 'easy',
    spice: 'mild',
    protein: 'low',
    costBand: '₹',
    tags: ['Quick', 'Regional', 'Budget', 'Tiffin box'],
    ingredients: [
      { qty: 400, unit: 'g', item: 'cabbage', note: 'very finely shredded (about 4 cups)' },
      { qty: 0.5, unit: 'cup', item: 'fresh grated coconut' },
      { qty: 4, unit: 'piece', item: 'shallots (small onions)', note: 'roughly chopped' },
      { qty: 2, unit: 'piece', item: 'green chillies' },
      { qty: 1, unit: 'clove', item: 'garlic' },
      { qty: 0.5, unit: 'tsp', item: 'cumin seeds', note: 'for the coconut mix' },
      { qty: 0.25, unit: 'tsp', item: 'turmeric powder' },
      { qty: 1.5, unit: 'tbsp', item: 'coconut oil' },
      { qty: 1, unit: 'tsp', item: 'mustard seeds' },
      { qty: 1, unit: 'tsp', item: 'urad dal' },
      { qty: 1, unit: 'piece', item: 'dried red chilli', note: 'broken' },
      { qty: 2, unit: 'sprig', item: 'curry leaves' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'Pulse the coconut, shallots, green chillies, garlic, cumin and turmeric in a mixer two or three times without water into a coarse, crumbly mix — it should not become a paste.',
      },
      {
        text: 'Heat the coconut oil in a wide kadai on medium, add the mustard seeds and let them splutter, then add the urad dal, red chilli and curry leaves and fry until the dal is golden.',
        timerMin: 2,
      },
      {
        text: 'Add the shredded cabbage and salt, toss well, then cover and cook on low heat in its own steam, stirring once or twice, until it just wilts.',
        timerMin: 4,
      },
      {
        text: 'Make a well in the centre, add the coconut mix, cover it with cabbage from the sides and let it steam covered for 2 minutes without stirring.',
        timerMin: 2,
      },
      {
        text: 'Uncover, mix everything together and stir-fry on medium for 2 minutes until the cabbage is tender-crisp and there is no moisture left in the pan.',
        timerMin: 2,
      },
      {
        text: 'Check salt and serve warm with rice, sambar or rasam, or pack it into a tiffin with chapati.',
      },
    ],
    nutrition: { kcal: 150, proteinG: 3, carbsG: 11, fatG: 11, fibreG: 5 },
  },
  {
    id: 'baingan-bharta',
    name: 'Punjabi Baingan Bharta',
    cuisine: 'Punjabi',
    dietMode: 'vegan',
    description:
      'Smoky fire-roasted brinjal mashed and cooked down with onion, tomato, garlic and green chilli — rustic Punjabi comfort with rotis.',
    servings: 3,
    prepMinutes: 10,
    cookMinutes: 35,
    difficulty: 'easy',
    spice: 'medium',
    protein: 'low',
    costBand: '₹',
    tags: ['Regional', 'Budget'],
    ingredients: [
      { qty: 1, unit: 'piece', item: 'large bharta brinjal (about 500 g)', note: 'washed and dried' },
      { qty: 1, unit: 'tsp', item: 'oil', note: 'to rub on the brinjal' },
      { qty: 2, unit: 'piece', item: 'onions (medium)', note: 'finely chopped' },
      { qty: 2, unit: 'piece', item: 'tomatoes (medium)', note: 'finely chopped' },
      { qty: 5, unit: 'clove', item: 'garlic', note: 'finely chopped' },
      { qty: 1, unit: 'inch', item: 'ginger', note: 'finely chopped' },
      { qty: 2, unit: 'piece', item: 'green chillies', note: 'finely chopped' },
      { qty: 1, unit: 'tsp', item: 'cumin seeds' },
      { qty: 0.25, unit: 'tsp', item: 'turmeric powder' },
      { qty: 1, unit: 'tsp', item: 'red chilli powder' },
      { qty: 1, unit: 'tsp', item: 'coriander powder' },
      { qty: 0.5, unit: 'tsp', item: 'garam masala powder' },
      { qty: 2.5, unit: 'tbsp', item: 'mustard oil or any oil' },
      { qty: 3, unit: 'tbsp', item: 'coriander leaves', note: 'chopped' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'Make 3–4 small slits in the brinjal (so it does not burst), rub it all over with a teaspoon of oil and place it directly on a gas flame on medium.',
      },
      {
        text: 'Roast, turning every 3–4 minutes with tongs, until the skin is charred and blistered all over and the brinjal collapses and feels completely soft when pressed.',
        timerMin: 15,
      },
      {
        text: 'Cover the roasted brinjal with a bowl for 5 minutes to steam, then peel off the charred skin under a trickle of water, remove the stem and mash the flesh with a fork.',
        timerMin: 5,
      },
      {
        text: 'Heat the mustard oil in a kadai until it just smokes, lower the heat, add the cumin, then the garlic, ginger and green chillies and sauté for a minute until the garlic turns light golden.',
      },
      {
        text: 'Add the onions and fry until soft and golden, then add the tomatoes with turmeric, chilli powder, coriander powder and salt and cook until the tomatoes break down and oil separates.',
        timerMin: 10,
      },
      {
        text: 'Add the mashed brinjal, mix well and cook on medium-low, stirring and mashing, until it looks thick and glossy and no longer watery.',
        timerMin: 6,
      },
      {
        text: 'Stir in the garam masala and coriander leaves and serve hot with phulka, paratha or makki di roti and sliced onion.',
      },
    ],
    nutrition: { kcal: 170, proteinG: 3, carbsG: 17, fatG: 11, fibreG: 7 },
  },
  {
    id: 'soya-keema-matar',
    name: 'Soya Keema Matar',
    cuisine: 'North Indian',
    dietMode: 'vegan',
    description:
      'Soya granules and green peas cooked down in a spiced onion-tomato masala until dry and rich — a high-protein keema for rotis or pav.',
    servings: 3,
    prepMinutes: 15,
    cookMinutes: 25,
    difficulty: 'easy',
    spice: 'medium',
    protein: 'high',
    costBand: '₹',
    tags: ['High protein', 'Budget', 'Tiffin box'],
    ingredients: [
      { qty: 1, unit: 'cup', item: 'soya granules (about 100 g)' },
      { qty: 0.75, unit: 'cup', item: 'green peas', note: 'fresh or frozen' },
      { qty: 2, unit: 'piece', item: 'onions (medium)', note: 'finely chopped' },
      { qty: 2, unit: 'piece', item: 'tomatoes (medium)', note: 'pureed' },
      { qty: 1, unit: 'tbsp', item: 'ginger-garlic paste' },
      { qty: 2, unit: 'piece', item: 'green chillies', note: 'finely chopped' },
      { qty: 1, unit: 'tsp', item: 'cumin seeds' },
      { qty: 1, unit: 'piece', item: 'bay leaf' },
      { qty: 0.5, unit: 'tsp', item: 'turmeric powder' },
      { qty: 1, unit: 'tsp', item: 'Kashmiri red chilli powder' },
      { qty: 1.5, unit: 'tsp', item: 'coriander powder' },
      { qty: 1, unit: 'tsp', item: 'garam masala powder' },
      { qty: 0.5, unit: 'tsp', item: 'kasuri methi', note: 'crushed between palms' },
      { qty: 2.5, unit: 'tbsp', item: 'oil' },
      { qty: 3, unit: 'tbsp', item: 'coriander leaves', note: 'chopped' },
      { qty: 1, unit: 'tbsp', item: 'lemon juice' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'Soak the soya granules in 2 cups of hot water with a pinch of salt until soft and doubled in size.',
        timerMin: 10,
      },
      {
        text: 'Drain, rinse twice in fresh water to remove the raw soya smell, then squeeze out as much water as you can with your hands.',
      },
      {
        text: 'Heat the oil in a kadai on medium, add the cumin and bay leaf, then the onions, and fry until golden brown.',
        timerMin: 7,
      },
      {
        text: 'Add the ginger-garlic paste and green chillies and fry for a minute, then add the tomato puree with turmeric, chilli powder, coriander powder and salt, and cook until the oil separates from the masala.',
        timerMin: 7,
      },
      {
        text: 'Add the squeezed soya granules and peas, mix well and stir-fry on medium for 3 minutes so the soya browns slightly and absorbs the masala.',
        timerMin: 3,
      },
      {
        text: 'Add half a cup of water, cover and simmer on low until the peas are tender and the keema is moist but not watery.',
        timerMin: 7,
      },
      {
        text: 'Stir in the garam masala and kasuri methi, cook uncovered for a minute more, then finish with lemon juice and coriander and serve with roti, paratha or toasted pav.',
      },
    ],
    nutrition: { kcal: 330, proteinG: 22, carbsG: 26, fatG: 14, fibreG: 10 },
  },
]
