import type { RecipeContent } from '../../domain/food/recipe'

export const recipesA: RecipeContent[] = [
  {
    id: 'chettinad-soya-curry',
    name: 'Chettinad Soya Curry with Foxtail Millet',
    cuisine: 'Chettinad',
    dietMode: 'vegetarian',
    description:
      'Chewy soya chunks simmered in a fiery, freshly roasted Chettinad masala of pepper, fennel, star anise and coconut, served over fluffy foxtail millet.',
    servings: 3,
    prepMinutes: 20,
    cookMinutes: 35,
    difficulty: 'medium',
    spice: 'fiery',
    protein: 'high',
    costBand: '₹',
    tags: ['High protein', 'Regional', 'Budget'],
    ingredients: [
      { qty: 100, unit: 'g', item: 'soya chunks' },
      { qty: 1, unit: 'cup', item: 'foxtail millet (thinai)', note: 'rinsed well' },
      { qty: 2.5, unit: 'cup', item: 'water', note: 'for the millet' },
      { qty: 2, unit: 'tbsp', item: 'coriander seeds' },
      { qty: 1, unit: 'tsp', item: 'fennel seeds' },
      { qty: 1, unit: 'tsp', item: 'cumin seeds' },
      { qty: 1, unit: 'tsp', item: 'black peppercorns' },
      { qty: 5, unit: 'piece', item: 'dry red chillies' },
      { qty: 1, unit: 'inch', item: 'cinnamon stick' },
      { qty: 3, unit: 'piece', item: 'cloves' },
      { qty: 1, unit: 'piece', item: 'star anise' },
      { qty: 1, unit: 'tsp', item: 'kalpasi (stone flower)', note: 'optional but traditional' },
      { qty: 0.25, unit: 'cup', item: 'fresh grated coconut' },
      { qty: 2, unit: 'tbsp', item: 'gingelly (sesame) oil' },
      { qty: 1, unit: 'tsp', item: 'fennel seeds', note: 'for tempering' },
      { qty: 2, unit: 'sprig', item: 'curry leaves' },
      { qty: 1, unit: 'piece', item: 'large onion', note: 'finely chopped' },
      { qty: 2, unit: 'piece', item: 'tomatoes', note: 'finely chopped' },
      { qty: 1, unit: 'tbsp', item: 'ginger-garlic paste' },
      { qty: 0.25, unit: 'tsp', item: 'turmeric powder' },
      { qty: null, unit: 'to taste', item: 'salt' },
      { qty: null, unit: 'to taste', item: 'coriander leaves', note: 'chopped, to garnish' },
    ],
    steps: [
      {
        text: 'Bring a pot of water to a boil, add the soya chunks with a pinch of salt and leave them for 10 minutes until soft and doubled in size. Drain, rinse in cold water and squeeze each handful completely dry.',
        timerMin: 10,
      },
      {
        text: 'Cook the millet: bring 2.5 cups water and a pinch of salt to a boil, add the rinsed foxtail millet, cover and cook on the lowest heat until the water is absorbed. Rest covered 5 minutes, then fluff with a fork.',
        timerMin: 15,
      },
      {
        text: 'In a dry pan on low-medium heat, roast the coriander seeds, fennel, cumin, peppercorns, red chillies, cinnamon, cloves, star anise and kalpasi, stirring, until fragrant and a shade darker. Add the coconut and roast until it turns light golden.',
        timerMin: 5,
      },
      {
        text: 'Cool the roasted masala, then grind it to a smooth paste with about 0.5 cup water.',
      },
      {
        text: 'Heat the gingelly oil in a kadai, add the tempering fennel and curry leaves, then the onion. Fry on medium heat until the onion is golden brown.',
        timerMin: 7,
      },
      {
        text: 'Add the ginger-garlic paste and fry until the raw smell goes, then add the tomatoes, turmeric and salt. Cook until the tomatoes are completely mushy and the oil starts to separate at the edges.',
        timerMin: 6,
      },
      {
        text: 'Stir in the ground masala and cook for 2–3 minutes, then add the squeezed soya chunks and 1 cup water. Cover and simmer on low heat until the gravy thickens and clings to the chunks.',
        timerMin: 12,
      },
      {
        text: 'Taste and adjust salt, scatter coriander leaves over the curry and serve hot alongside the millet.',
      },
    ],
    nutrition: { kcal: 520, proteinG: 25, carbsG: 62, fatG: 17, fibreG: 11 },
  },
  {
    id: 'kerala-kadala-appam',
    name: 'Kerala Kadala Curry with Appam',
    cuisine: 'Kerala',
    dietMode: 'vegan',
    description:
      'Lacy, soft-centred appams made from fermented rice and coconut batter, paired with black chickpeas simmered in a dark roasted-coconut gravy.',
    servings: 4,
    prepMinutes: 30,
    cookMinutes: 60,
    difficulty: 'involved',
    spice: 'medium',
    protein: 'medium',
    costBand: '₹',
    tags: ['Regional', 'Weekend', 'Breakfast'],
    ingredients: [
      { qty: 1.5, unit: 'cup', item: 'raw rice (ponni or sona masoori)', note: 'soaked 5 hours' },
      { qty: 0.5, unit: 'cup', item: 'cooked rice' },
      { qty: 0.75, unit: 'cup', item: 'fresh grated coconut', note: 'for the batter' },
      { qty: 0.5, unit: 'tsp', item: 'instant dry yeast' },
      { qty: 2, unit: 'tbsp', item: 'sugar' },
      { qty: 0.75, unit: 'cup', item: 'black chickpeas (kala chana)', note: 'soaked overnight' },
      { qty: 0.75, unit: 'cup', item: 'fresh grated coconut', note: 'for the curry' },
      { qty: 1.5, unit: 'tbsp', item: 'coriander powder' },
      { qty: 1, unit: 'tsp', item: 'Kashmiri red chilli powder' },
      { qty: 0.5, unit: 'tsp', item: 'garam masala' },
      { qty: 0.25, unit: 'tsp', item: 'turmeric powder' },
      { qty: 2, unit: 'tbsp', item: 'coconut oil' },
      { qty: 1, unit: 'tsp', item: 'mustard seeds' },
      { qty: 10, unit: 'piece', item: 'shallots', note: 'thinly sliced' },
      { qty: 1, unit: 'inch', item: 'ginger', note: 'finely chopped' },
      { qty: 2, unit: 'piece', item: 'green chillies', note: 'slit' },
      { qty: 2, unit: 'sprig', item: 'curry leaves' },
      { qty: 1, unit: 'piece', item: 'tomato', note: 'chopped' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'The night before, soak the black chickpeas in plenty of water. Separately soak the raw rice for about 5 hours before grinding.',
        timerMin: 300,
      },
      {
        text: 'Grind the drained rice, cooked rice, 0.75 cup coconut, yeast and sugar with just enough water to make a smooth, pourable batter like thick pancake batter. Cover loosely and leave in a warm place until doubled and bubbly.',
        timerMin: 480,
      },
      {
        text: 'Pressure-cook the soaked chickpeas with 2 cups water, turmeric and salt for 5–6 whistles (about 20 minutes) until they mash easily between your fingers. Keep the cooking liquid.',
        timerMin: 20,
      },
      {
        text: 'Dry-roast the 0.75 cup coconut for the curry in a pan on low-medium heat, stirring constantly, until deep brown and aromatic. Add the coriander powder, chilli powder and garam masala, roast 30 seconds, cool, and grind to a fine paste with a little water.',
        timerMin: 10,
      },
      {
        text: 'Heat the coconut oil, crackle the mustard seeds, then add the shallots, ginger, green chillies and curry leaves. Sauté on medium heat until the shallots turn golden, then add the tomato and cook until soft.',
        timerMin: 8,
      },
      {
        text: 'Add the roasted coconut paste, the cooked chickpeas and their liquid. Simmer uncovered, stirring now and then, until the gravy is thick and glossy; mash a few chickpeas against the pan to thicken it.',
        timerMin: 15,
      },
      {
        text: 'Stir a pinch of salt into the fermented batter. Heat an appachatti (or small non-stick kadai) on medium heat, pour in a ladle of batter and immediately swirl the pan so it coats the sides thinly, leaving it thicker in the centre.',
      },
      {
        text: 'Cover and cook on medium-low heat for about 2 minutes, until the edges are crisp and lacy and the centre is spongy and set. Lift out without flipping and repeat with the rest of the batter; serve hot with the kadala curry.',
        timerMin: 2,
      },
    ],
    nutrition: { kcal: 600, proteinG: 14, carbsG: 88, fatG: 20, fibreG: 12 },
  },
  {
    id: 'millet-sambar-combo',
    name: 'Samai Millet with Vegetable Sambar',
    cuisine: 'Tamil',
    dietMode: 'vegan',
    description:
      'Soft little millet with a tangy, home-style toor dal sambar full of drumstick and vegetables — an everyday Tamil lunch that is light yet filling.',
    servings: 3,
    prepMinutes: 10,
    cookMinutes: 30,
    difficulty: 'easy',
    spice: 'medium',
    protein: 'medium',
    costBand: '₹',
    tags: ['Budget', 'Regional', 'Tiffin box'],
    ingredients: [
      { qty: 1, unit: 'cup', item: 'little millet (samai)', note: 'rinsed' },
      { qty: 2.5, unit: 'cup', item: 'water', note: 'for the millet' },
      { qty: 0.5, unit: 'cup', item: 'toor dal', note: 'rinsed' },
      { qty: 0.25, unit: 'tsp', item: 'turmeric powder' },
      { qty: 1, unit: 'piece', item: 'drumstick', note: 'cut into 3-inch pieces' },
      { qty: 1, unit: 'piece', item: 'carrot', note: 'cubed' },
      { qty: 8, unit: 'piece', item: 'shallots', note: 'peeled' },
      { qty: 1, unit: 'piece', item: 'tomato', note: 'chopped' },
      { qty: 1, unit: 'tbsp', item: 'tamarind', note: 'soaked in 1 cup warm water, juice extracted' },
      { qty: 1.5, unit: 'tbsp', item: 'sambar powder' },
      { qty: 1, unit: 'tbsp', item: 'gingelly (sesame) oil' },
      { qty: 1, unit: 'tsp', item: 'mustard seeds' },
      { qty: 0.25, unit: 'tsp', item: 'fenugreek seeds' },
      { qty: 2, unit: 'piece', item: 'dry red chillies' },
      { qty: 1, unit: 'pinch', item: 'asafoetida' },
      { qty: 1, unit: 'sprig', item: 'curry leaves' },
      { qty: null, unit: 'to taste', item: 'salt' },
      { qty: null, unit: 'to taste', item: 'coriander leaves', note: 'chopped' },
    ],
    steps: [
      {
        text: 'Pressure-cook the toor dal with 1.5 cups water and the turmeric for 4 whistles (about 12 minutes), then mash it smooth with the back of a ladle.',
        timerMin: 12,
      },
      {
        text: 'Meanwhile bring 2.5 cups water and a pinch of salt to a boil, add the millet, cover and cook on low heat until the water is absorbed. Turn off and rest covered for 5 minutes.',
        timerMin: 15,
      },
      {
        text: 'In a pot, heat the oil, add the mustard seeds and let them splutter, then add fenugreek, red chillies, asafoetida and curry leaves.',
      },
      {
        text: 'Add the shallots and sauté for 2 minutes, then the tomato, drumstick and carrot. Pour in the tamarind water, the sambar powder, salt and 1 cup water, and simmer until the vegetables are tender and the raw tamarind smell is gone.',
        timerMin: 10,
      },
      {
        text: 'Stir in the mashed dal and simmer on low heat until the sambar comes together and thickens slightly; add hot water if it gets too thick.',
        timerMin: 5,
      },
      {
        text: 'Finish with chopped coriander and serve the sambar ladled generously over the warm millet.',
      },
    ],
    nutrition: { kcal: 395, proteinG: 13, carbsG: 66, fatG: 7, fibreG: 10 },
  },
  {
    id: 'paneer-bhurji-wrap',
    name: 'Paneer Bhurji Wrap',
    cuisine: 'North Indian',
    dietMode: 'vegetarian',
    description:
      'Soft crumbled paneer scrambled with onion, capsicum and tomato, rolled into warm whole-wheat rotis for a quick, protein-packed meal.',
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 15,
    difficulty: 'easy',
    spice: 'mild',
    protein: 'high',
    costBand: '₹₹',
    tags: ['High protein', 'Quick', 'Kid-friendly', 'Tiffin box'],
    ingredients: [
      { qty: 200, unit: 'g', item: 'paneer', note: 'crumbled' },
      { qty: 4, unit: 'piece', item: 'whole-wheat rotis or wraps', note: '8-inch' },
      { qty: 1, unit: 'tbsp', item: 'oil' },
      { qty: 0.5, unit: 'tsp', item: 'cumin seeds' },
      { qty: 1, unit: 'piece', item: 'medium onion', note: 'finely chopped' },
      { qty: 0.5, unit: 'piece', item: 'green capsicum', note: 'finely chopped' },
      { qty: 1, unit: 'piece', item: 'tomato', note: 'finely chopped' },
      { qty: 1, unit: 'piece', item: 'green chilli', note: 'finely chopped' },
      { qty: 1, unit: 'tsp', item: 'ginger', note: 'grated' },
      { qty: 0.25, unit: 'tsp', item: 'turmeric powder' },
      { qty: 0.5, unit: 'tsp', item: 'Kashmiri red chilli powder' },
      { qty: 1, unit: 'tsp', item: 'pav bhaji masala' },
      { qty: null, unit: 'to taste', item: 'salt' },
      { qty: 2, unit: 'tbsp', item: 'coriander leaves', note: 'chopped' },
      { qty: 1, unit: 'tsp', item: 'lemon juice' },
    ],
    steps: [
      {
        text: 'Heat the oil in a pan on medium heat, add the cumin seeds and let them sizzle, then add the onion and sauté until soft and translucent.',
        timerMin: 3,
      },
      {
        text: 'Add the green chilli, ginger and capsicum and cook for 2 minutes until the capsicum softens slightly but keeps a little crunch.',
        timerMin: 2,
      },
      {
        text: 'Add the tomato, turmeric, chilli powder, pav bhaji masala and salt, and cook until the tomato breaks down into a thick masala.',
        timerMin: 3,
      },
      {
        text: 'Add the crumbled paneer and toss gently for 2–3 minutes so it absorbs the masala; do not overcook or the paneer turns rubbery. Finish with coriander and lemon juice.',
        timerMin: 3,
      },
      {
        text: 'Warm each roti on a hot tawa for about 20 seconds per side so it becomes pliable.',
      },
      {
        text: 'Spoon a quarter of the bhurji along the centre of each roti, roll it up tightly, and toast seam-side down on the tawa for 30 seconds to seal. Cut in half and serve warm.',
      },
    ],
    nutrition: { kcal: 665, proteinG: 29, carbsG: 62, fatG: 32, fibreG: 9 },
  },
  {
    id: 'mushroom-biryani',
    name: 'Tamil-style Mushroom Biryani',
    cuisine: 'Tamil',
    dietMode: 'vegetarian',
    description:
      'Fragrant seeraga samba rice cooked with mushrooms in a green mint-coriander masala, the way it is made for Sunday lunch across Tamil Nadu.',
    servings: 4,
    prepMinutes: 25,
    cookMinutes: 35,
    difficulty: 'medium',
    spice: 'fiery',
    protein: 'medium',
    costBand: '₹₹',
    tags: ['Regional', 'Weekend', 'One-pot'],
    ingredients: [
      { qty: 2, unit: 'cup', item: 'seeraga samba rice', note: 'rinsed and soaked 20 minutes' },
      { qty: 400, unit: 'g', item: 'button mushrooms', note: 'halved or quartered' },
      { qty: 0.5, unit: 'cup', item: 'thick curd', note: 'whisked' },
      { qty: 1, unit: 'handful', item: 'mint leaves' },
      { qty: 1, unit: 'handful', item: 'coriander leaves' },
      { qty: 4, unit: 'piece', item: 'green chillies' },
      { qty: 1, unit: 'inch', item: 'ginger' },
      { qty: 8, unit: 'clove', item: 'garlic' },
      { qty: 2, unit: 'tbsp', item: 'ghee' },
      { qty: 2, unit: 'tbsp', item: 'oil' },
      { qty: 1, unit: 'inch', item: 'cinnamon stick' },
      { qty: 4, unit: 'piece', item: 'cloves' },
      { qty: 3, unit: 'piece', item: 'green cardamom' },
      { qty: 1, unit: 'piece', item: 'bay leaf' },
      { qty: 1, unit: 'piece', item: 'star anise' },
      { qty: 2, unit: 'piece', item: 'large onions', note: 'thinly sliced' },
      { qty: 2, unit: 'piece', item: 'tomatoes', note: 'chopped' },
      { qty: 1, unit: 'tsp', item: 'Kashmiri red chilli powder' },
      { qty: 1, unit: 'tsp', item: 'biryani masala' },
      { qty: 0.25, unit: 'tsp', item: 'turmeric powder' },
      { qty: 3, unit: 'cup', item: 'water' },
      { qty: 1, unit: 'tbsp', item: 'lemon juice' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'Rinse the seeraga samba rice 2–3 times and soak it in water; this short soak keeps the small grains separate.',
        timerMin: 20,
      },
      {
        text: 'Grind the mint, coriander, green chillies, ginger and garlic into a coarse paste with a splash of water.',
      },
      {
        text: 'Heat the ghee and oil in a heavy pot or pressure cooker on medium heat, add the cinnamon, cloves, cardamom, bay leaf and star anise, and fry for 30 seconds until fragrant.',
      },
      {
        text: 'Add the onions and fry, stirring, until they are golden brown at the edges. Add the green paste and cook until the raw smell disappears and it darkens slightly.',
        timerMin: 8,
      },
      {
        text: 'Add the tomatoes, chilli powder, biryani masala, turmeric and salt, and cook until the tomatoes are mushy and the oil separates.',
        timerMin: 5,
      },
      {
        text: 'Lower the heat, stir in the curd so it does not split, then add the mushrooms and cook for 4–5 minutes until they release their water and shrink a little.',
        timerMin: 5,
      },
      {
        text: 'Pour in 3 cups water and the lemon juice and taste — the water should taste slightly over-salted. Bring to a rolling boil and add the drained rice.',
      },
      {
        text: 'Pressure-cook for 1 whistle on medium heat, then turn off and let the pressure drop on its own (about 10 minutes). If cooking in a pot, cover tightly and cook on the lowest heat for 15–18 minutes.',
        timerMin: 15,
      },
      {
        text: 'Open, gently fluff the rice with a fork from the edges so the grains stay whole, and serve hot with onion raita.',
      },
    ],
    nutrition: { kcal: 530, proteinG: 12, carbsG: 82, fatG: 17, fibreG: 5 },
  },
  {
    id: 'avial-red-rice',
    name: 'Avial with Kerala Red Rice',
    cuisine: 'Kerala',
    dietMode: 'vegan',
    description:
      'A medley of Kerala vegetables folded into a coarse coconut, cumin and green-chilli paste, soured with raw mango and finished with raw coconut oil, over nutty matta rice.',
    servings: 3,
    prepMinutes: 25,
    cookMinutes: 45,
    difficulty: 'medium',
    spice: 'mild',
    protein: 'low',
    costBand: '₹',
    tags: ['Regional', 'Budget'],
    ingredients: [
      { qty: 1, unit: 'cup', item: 'Kerala matta (red) rice', note: 'rinsed and soaked 30 minutes' },
      { qty: 6, unit: 'cup', item: 'water', note: 'for the rice' },
      { qty: 1, unit: 'piece', item: 'raw banana', note: 'peeled, cut into 2-inch batons' },
      { qty: 100, unit: 'g', item: 'elephant yam', note: 'peeled, cut into batons' },
      { qty: 1, unit: 'piece', item: 'drumstick', note: 'cut into 2-inch pieces' },
      { qty: 1, unit: 'piece', item: 'carrot', note: 'cut into batons' },
      { qty: 8, unit: 'piece', item: 'beans', note: 'cut into 2-inch pieces' },
      { qty: 100, unit: 'g', item: 'ash gourd', note: 'cut into batons' },
      { qty: 0.5, unit: 'piece', item: 'raw mango', note: 'sour variety, cut into batons (or 1 tsp tamarind pulp)' },
      { qty: 0.25, unit: 'tsp', item: 'turmeric powder' },
      { qty: 1, unit: 'cup', item: 'fresh grated coconut' },
      { qty: 1, unit: 'tsp', item: 'cumin seeds' },
      { qty: 3, unit: 'piece', item: 'green chillies' },
      { qty: 3, unit: 'piece', item: 'shallots' },
      { qty: 2, unit: 'tbsp', item: 'coconut oil', note: 'raw, unheated' },
      { qty: 2, unit: 'sprig', item: 'curry leaves' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'Rinse the red rice and soak it for 30 minutes; this shortens the cooking time for the hard matta grains.',
        timerMin: 30,
      },
      {
        text: 'Boil the rice in 6 cups of water like pasta on medium heat until the grains are soft but still separate, then drain off the excess water. (In a pressure cooker, use 4 cups water and cook for 5–6 whistles, about 25 minutes.)',
        timerMin: 35,
      },
      {
        text: 'Meanwhile, grind the coconut, cumin, green chillies and shallots coarsely with 2–3 tbsp water — it should look grainy, not a smooth paste.',
      },
      {
        text: 'Put the yam, raw banana and drumstick in a wide pan with the turmeric, salt and 0.5 cup water, cover and cook on medium heat for 5 minutes, as these take longest.',
        timerMin: 5,
      },
      {
        text: 'Add the carrot, beans, ash gourd and raw mango, cover and cook until every vegetable is just tender but still holds its shape; stir gently so they do not break.',
        timerMin: 7,
      },
      {
        text: 'Add the coconut mixture, fold it through gently and cook uncovered on low heat until the mix is thick and almost dry, with no liquid pooling at the bottom.',
        timerMin: 3,
      },
      {
        text: 'Turn off the heat, crush the curry leaves in your hand over the avial and drizzle with the raw coconut oil. Cover for 5 minutes so the aroma soaks in, then serve with the red rice.',
      },
    ],
    nutrition: { kcal: 485, proteinG: 8, carbsG: 72, fatG: 18, fibreG: 9 },
  },
  {
    id: 'andhra-gutti-vankaya',
    name: 'Andhra Gutti Vankaya Kura',
    cuisine: 'Andhra',
    dietMode: 'vegan',
    description:
      'Small purple brinjals stuffed with a roasted peanut, sesame and coconut masala and slow-cooked in tangy tamarind until meltingly soft.',
    servings: 3,
    prepMinutes: 25,
    cookMinutes: 30,
    difficulty: 'medium',
    spice: 'fiery',
    protein: 'low',
    costBand: '₹',
    tags: ['Regional', 'Budget'],
    ingredients: [
      { qty: 400, unit: 'g', item: 'small purple brinjals (about 10)', note: 'stems trimmed, slit in a plus shape' },
      { qty: 3, unit: 'tbsp', item: 'raw peanuts' },
      { qty: 2, unit: 'tbsp', item: 'white sesame seeds' },
      { qty: 2, unit: 'tbsp', item: 'dry coconut (kopra)', note: 'grated' },
      { qty: 1, unit: 'tbsp', item: 'coriander seeds' },
      { qty: 1, unit: 'tsp', item: 'cumin seeds' },
      { qty: 1, unit: 'piece', item: 'medium onion', note: 'roughly chopped' },
      { qty: 1, unit: 'tsp', item: 'ginger-garlic paste' },
      { qty: 1.5, unit: 'tsp', item: 'red chilli powder' },
      { qty: 0.25, unit: 'tsp', item: 'turmeric powder' },
      { qty: 1, unit: 'tbsp', item: 'tamarind', note: 'soaked in 0.5 cup warm water, pulp extracted' },
      { qty: 1, unit: 'tsp', item: 'jaggery', note: 'grated' },
      { qty: 3, unit: 'tbsp', item: 'groundnut oil' },
      { qty: 0.5, unit: 'tsp', item: 'mustard seeds' },
      { qty: 0.5, unit: 'tsp', item: 'cumin seeds', note: 'for tempering' },
      { qty: 1, unit: 'sprig', item: 'curry leaves' },
      { qty: null, unit: 'to taste', item: 'salt' },
      { qty: null, unit: 'to taste', item: 'coriander leaves', note: 'chopped' },
    ],
    steps: [
      {
        text: 'Slit each brinjal into four from the bottom, keeping the stem end intact, and drop them into salted water so they do not darken.',
      },
      {
        text: 'Dry-roast the peanuts on low-medium heat until they crackle and the skins blister, then add the sesame, dry coconut, coriander seeds and cumin and roast until the sesame just starts to pop. Let everything cool.',
        timerMin: 6,
      },
      {
        text: 'Grind the roasted mix with the onion, ginger-garlic paste, chilli powder, turmeric, jaggery and salt into a thick, slightly coarse paste using very little water.',
      },
      {
        text: 'Drain the brinjals and stuff each one generously with the masala, pressing it into the slits. Keep the leftover masala aside.',
      },
      {
        text: 'Heat the groundnut oil in a wide, heavy pan, splutter the mustard seeds, then add cumin and curry leaves. Arrange the stuffed brinjals in a single layer and fry on medium-low heat, turning gently, until the skins wrinkle all over.',
        timerMin: 8,
      },
      {
        text: 'Mix the leftover masala with the tamarind water and 0.5 cup water, pour it over the brinjals, cover and simmer on low heat, turning once, until the brinjals are completely soft and the oil floats on top of the thick gravy.',
        timerMin: 20,
      },
      {
        text: 'Taste for salt and tang, garnish with coriander and serve hot with steamed rice.',
      },
    ],
    nutrition: { kcal: 285, proteinG: 6, carbsG: 17, fatG: 22, fibreG: 8 },
  },
  {
    id: 'karnataka-bisi-bele-bath',
    name: 'Karnataka Bisi Bele Bath',
    cuisine: 'Karnataka',
    dietMode: 'vegetarian',
    description:
      'Rice, toor dal and vegetables cooked into a hot, tangy, spiced porridge with freshly ground bisi bele bath powder and a ghee-cashew finish.',
    servings: 4,
    prepMinutes: 20,
    cookMinutes: 40,
    difficulty: 'medium',
    spice: 'medium',
    protein: 'medium',
    costBand: '₹',
    tags: ['Regional', 'Weekend', 'One-pot'],
    ingredients: [
      { qty: 0.75, unit: 'cup', item: 'sona masoori rice', note: 'rinsed' },
      { qty: 0.5, unit: 'cup', item: 'toor dal', note: 'rinsed' },
      { qty: 0.25, unit: 'tsp', item: 'turmeric powder' },
      { qty: 1, unit: 'piece', item: 'carrot', note: 'cubed' },
      { qty: 10, unit: 'piece', item: 'beans', note: 'chopped' },
      { qty: 0.25, unit: 'cup', item: 'green peas' },
      { qty: 8, unit: 'piece', item: 'shallots', note: 'peeled' },
      { qty: 1, unit: 'tbsp', item: 'chana dal', note: 'for the spice powder' },
      { qty: 1, unit: 'tsp', item: 'urad dal', note: 'for the spice powder' },
      { qty: 2, unit: 'tbsp', item: 'coriander seeds' },
      { qty: 6, unit: 'piece', item: 'byadgi dry red chillies' },
      { qty: 1, unit: 'inch', item: 'cinnamon stick' },
      { qty: 3, unit: 'piece', item: 'cloves' },
      { qty: 0.25, unit: 'tsp', item: 'fenugreek seeds' },
      { qty: 2, unit: 'tbsp', item: 'dry coconut (kopra)', note: 'grated' },
      { qty: 1, unit: 'tbsp', item: 'tamarind', note: 'soaked in 1 cup warm water, pulp extracted' },
      { qty: 1, unit: 'tsp', item: 'jaggery' },
      { qty: 3, unit: 'tbsp', item: 'ghee' },
      { qty: 1, unit: 'tsp', item: 'mustard seeds' },
      { qty: 12, unit: 'piece', item: 'cashews' },
      { qty: 1, unit: 'sprig', item: 'curry leaves' },
      { qty: 1, unit: 'pinch', item: 'asafoetida' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'Pressure-cook the rice and toor dal together with 4 cups water and the turmeric for 5 whistles (about 15 minutes) until very soft. Mash lightly once the pressure drops.',
        timerMin: 15,
      },
      {
        text: 'For the bisi bele bath powder, heat 1 tsp of the ghee and roast the chana dal, urad dal, coriander seeds, red chillies, cinnamon, cloves and fenugreek on low heat until the dals are golden. Add the dry coconut and roast 1 minute more, cool, and grind to a fine powder.',
        timerMin: 6,
      },
      {
        text: 'In a large pot, cook the carrot, beans, peas and shallots in 1 cup water with salt until tender.',
        timerMin: 8,
      },
      {
        text: 'Add the tamarind water, jaggery and 3 tbsp of the ground powder to the vegetables and simmer until the raw tamarind smell goes.',
        timerMin: 5,
      },
      {
        text: 'Stir in the mashed rice-dal and 1 cup hot water, and simmer on low heat, stirring often so it does not catch, until it is a loose, porridge-like consistency. It thickens as it cools, so keep it slightly runny.',
        timerMin: 7,
      },
      {
        text: 'For the tempering, heat the remaining ghee, splutter the mustard seeds, then fry the cashews until golden and add the curry leaves and asafoetida. Pour it over the bisi bele bath, stir, and serve hot with boondi or papad.',
      },
    ],
    nutrition: { kcal: 400, proteinG: 11, carbsG: 55, fatG: 15, fibreG: 7 },
  },
  {
    id: 'telangana-sakinalu-dal-khichdi',
    name: 'Telangana Sarva Pindi',
    cuisine: 'Telangana',
    dietMode: 'vegan',
    description:
      'A rustic Telangana rice-flour griddle cake studded with chana dal, peanuts and sesame, pressed thin in a kadai and cooked crisp with groundnut oil.',
    servings: 3,
    prepMinutes: 20,
    cookMinutes: 30,
    difficulty: 'medium',
    spice: 'medium',
    protein: 'medium',
    costBand: '₹',
    tags: ['Regional', 'Budget', 'Breakfast', 'Tiffin box'],
    ingredients: [
      { qty: 1.5, unit: 'cup', item: 'rice flour' },
      { qty: 2, unit: 'tbsp', item: 'chana dal', note: 'soaked 1 hour' },
      { qty: 3, unit: 'tbsp', item: 'roasted peanuts', note: 'coarsely crushed' },
      { qty: 1, unit: 'tbsp', item: 'white sesame seeds' },
      { qty: 1, unit: 'piece', item: 'medium onion', note: 'finely chopped' },
      { qty: 2, unit: 'piece', item: 'green chillies', note: 'finely chopped' },
      { qty: 1, unit: 'inch', item: 'ginger', note: 'grated' },
      { qty: 1, unit: 'sprig', item: 'curry leaves', note: 'chopped' },
      { qty: 2, unit: 'tbsp', item: 'coriander leaves', note: 'chopped' },
      { qty: 0.5, unit: 'tsp', item: 'cumin seeds' },
      { qty: 1, unit: 'tsp', item: 'red chilli powder' },
      { qty: 3, unit: 'tbsp', item: 'groundnut oil' },
      { qty: 0.75, unit: 'cup', item: 'warm water', note: 'approximately' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'Soak the chana dal in water for about 1 hour, then drain well.',
        timerMin: 60,
      },
      {
        text: 'In a bowl, mix the rice flour, drained chana dal, peanuts, sesame, onion, green chillies, ginger, curry leaves, coriander, cumin, chilli powder, salt and 1 tbsp oil.',
      },
      {
        text: 'Add warm water a little at a time and knead into a soft, non-sticky dough that holds together without cracking. Divide into 3 portions.',
      },
      {
        text: 'Grease a cold, heavy kadai or thick tawa with 1 tsp oil. Place one portion in the centre and, with wet fingers, press it out into a thin, even round about 0.25 inch thick.',
      },
      {
        text: 'Poke 5–6 holes in the dough with your finger and pour a few drops of oil into each hole and around the edges.',
      },
      {
        text: 'Put the kadai on medium heat, cover and cook until the underside is golden and crisp and the top looks dry and cooked through. There is no need to flip.',
        timerMin: 8,
      },
      {
        text: 'Loosen the edges with a spatula, lift out, and let the kadai cool slightly before pressing the next one (dough spreads badly on a hot pan). Serve warm with peanut chutney.',
      },
    ],
    nutrition: { kcal: 515, proteinG: 10, carbsG: 72, fatG: 21, fibreG: 5 },
  },
  {
    id: 'punjabi-rajma-chawal',
    name: 'Punjabi Rajma Chawal',
    cuisine: 'Punjabi',
    dietMode: 'vegan',
    description:
      'Creamy red kidney beans slow-simmered in a deep onion-tomato masala and served over steamed basmati — Punjab’s favourite Sunday comfort meal.',
    servings: 4,
    prepMinutes: 20,
    cookMinutes: 60,
    difficulty: 'medium',
    spice: 'medium',
    protein: 'high',
    costBand: '₹',
    tags: ['High protein', 'Regional', 'Weekend'],
    ingredients: [
      { qty: 1, unit: 'cup', item: 'rajma (red kidney beans)', note: 'soaked overnight' },
      { qty: 1.25, unit: 'cup', item: 'basmati rice', note: 'rinsed and soaked 20 minutes' },
      { qty: 3, unit: 'tbsp', item: 'mustard or sunflower oil' },
      { qty: 1, unit: 'tsp', item: 'cumin seeds' },
      { qty: 1, unit: 'piece', item: 'bay leaf' },
      { qty: 2, unit: 'piece', item: 'large onions', note: 'finely chopped' },
      { qty: 1, unit: 'tbsp', item: 'ginger-garlic paste' },
      { qty: 2, unit: 'piece', item: 'green chillies', note: 'slit' },
      { qty: 3, unit: 'piece', item: 'tomatoes', note: 'puréed' },
      { qty: 0.25, unit: 'tsp', item: 'turmeric powder' },
      { qty: 1, unit: 'tsp', item: 'Kashmiri red chilli powder' },
      { qty: 1.5, unit: 'tsp', item: 'coriander powder' },
      { qty: 1, unit: 'tsp', item: 'rajma masala or garam masala' },
      { qty: 1, unit: 'tsp', item: 'kasuri methi', note: 'crushed' },
      { qty: null, unit: 'to taste', item: 'salt' },
      { qty: 2, unit: 'tbsp', item: 'coriander leaves', note: 'chopped' },
    ],
    steps: [
      {
        text: 'Soak the rajma overnight in plenty of water (at least 8 hours); they should swell to about double their size.',
        timerMin: 480,
      },
      {
        text: 'Drain, add fresh water to cover by 2 inches with a little salt, and pressure-cook on high for 5–6 whistles, then on low heat for 15 minutes (about 30 minutes in total). The beans should crush easily between your fingers; keep the cooking liquid.',
        timerMin: 30,
      },
      {
        text: 'Heat the oil in a heavy pan, add cumin and bay leaf, then the onions. Fry on medium heat, stirring, until deep golden brown — this is what gives rajma its colour.',
        timerMin: 12,
      },
      {
        text: 'Add the ginger-garlic paste and green chillies and fry 1 minute, then add the tomato purée, turmeric, chilli powder, coriander powder and salt. Cook until the masala darkens and the oil separates at the edges.',
        timerMin: 10,
      },
      {
        text: 'Add the rajma with its cooking liquid, mash a spoonful of beans against the pan to thicken, and simmer uncovered on low heat until the gravy is thick and creamy.',
        timerMin: 20,
      },
      {
        text: 'While the rajma simmers, boil the drained basmati in plenty of salted water until just cooked, about 10–12 minutes, then drain and let it steam covered for 5 minutes.',
        timerMin: 12,
      },
      {
        text: 'Stir the rajma masala and crushed kasuri methi into the curry, simmer 2 more minutes, garnish with coriander and serve over the rice.',
      },
    ],
    nutrition: { kcal: 500, proteinG: 16, carbsG: 80, fatG: 12, fibreG: 14 },
  },
  {
    id: 'rajasthani-dal-baati',
    name: 'Rajasthani Dal Baati (Jain-friendly)',
    cuisine: 'Rajasthani',
    dietMode: 'vegetarian',
    description:
      'Crusty baked wheat baatis dunked in ghee and served with a tempered five-dal panchmel — made without onion, garlic or ginger so it suits a Jain kitchen.',
    servings: 4,
    prepMinutes: 30,
    cookMinutes: 50,
    difficulty: 'involved',
    spice: 'medium',
    protein: 'high',
    costBand: '₹₹',
    tags: ['Jain-friendly', 'Weekend', 'High protein', 'Regional'],
    ingredients: [
      { qty: 2, unit: 'cup', item: 'whole-wheat flour (atta)', note: 'coarse if available' },
      { qty: 2, unit: 'tbsp', item: 'fine semolina (rava)' },
      { qty: 4, unit: 'tbsp', item: 'ghee', note: 'melted, for the dough' },
      { qty: 0.5, unit: 'tsp', item: 'ajwain (carom seeds)' },
      { qty: 0.25, unit: 'tsp', item: 'baking soda' },
      { qty: 0.75, unit: 'cup', item: 'water', note: 'lukewarm, approximately' },
      { qty: 0.25, unit: 'cup', item: 'toor dal' },
      { qty: 0.25, unit: 'cup', item: 'chana dal' },
      { qty: 0.25, unit: 'cup', item: 'moong dal (yellow)' },
      { qty: 0.25, unit: 'tsp', item: 'turmeric powder' },
      { qty: 1, unit: 'tbsp', item: 'ghee', note: 'for the dal tadka' },
      { qty: 1, unit: 'tsp', item: 'cumin seeds' },
      { qty: 1, unit: 'pinch', item: 'asafoetida' },
      { qty: 2, unit: 'piece', item: 'dry red chillies' },
      { qty: 2, unit: 'piece', item: 'green chillies', note: 'slit' },
      { qty: 2, unit: 'piece', item: 'tomatoes', note: 'finely chopped' },
      { qty: 1, unit: 'tsp', item: 'red chilli powder' },
      { qty: 1, unit: 'tsp', item: 'coriander powder' },
      { qty: 0.5, unit: 'tsp', item: 'garam masala' },
      { qty: 3, unit: 'tbsp', item: 'ghee', note: 'melted, for dipping the baatis' },
      { qty: null, unit: 'to taste', item: 'salt' },
      { qty: 2, unit: 'tbsp', item: 'coriander leaves', note: 'chopped' },
    ],
    steps: [
      {
        text: 'Rinse the three dals together and soak them in warm water while you make the dough.',
        timerMin: 30,
      },
      {
        text: 'Mix the atta, semolina, ajwain, baking soda and salt, then rub in the 4 tbsp melted ghee with your fingertips until the flour holds together when pressed. Add lukewarm water gradually and knead into a firm, stiff dough. Cover and rest.',
        timerMin: 20,
      },
      {
        text: 'Preheat the oven to 200°C. Divide the dough into 10–12 lemon-sized balls, flatten slightly, and press a small dent in the centre of each with your thumb.',
      },
      {
        text: 'Bake the baatis on a tray, turning them halfway, until they are golden brown, crack slightly on top, and sound hollow when tapped.',
        timerMin: 35,
      },
      {
        text: 'Meanwhile pressure-cook the soaked dals with 3 cups water, turmeric and salt for 3 whistles (about 10 minutes); they should be soft but not completely mushy.',
        timerMin: 10,
      },
      {
        text: 'For the tadka, heat 1 tbsp ghee, add cumin, asafoetida, dry red chillies and green chillies, then the tomatoes, chilli powder and coriander powder. Cook until the tomatoes turn soft and the ghee separates.',
        timerMin: 5,
      },
      {
        text: 'Pour the cooked dal into the tadka, add garam masala and water to get a medium-thick consistency, and simmer on low heat so the flavours come together. Finish with coriander.',
        timerMin: 8,
      },
      {
        text: 'While the baatis are hot, press each one gently to crack it open and dip it in the melted ghee. Serve 2–3 baatis per person with a generous bowl of dal poured over them.',
      },
    ],
    nutrition: { kcal: 620, proteinG: 17, carbsG: 72, fatG: 30, fibreG: 11 },
  },
  {
    id: 'idli-sambar',
    name: 'Idli with Tiffin Sambar',
    cuisine: 'Tamil',
    dietMode: 'vegan',
    description:
      'Pillowy steamed idlis from a naturally fermented rice and urad batter, served with a light, shallot-studded tiffin sambar.',
    servings: 6,
    prepMinutes: 30,
    cookMinutes: 40,
    difficulty: 'medium',
    spice: 'mild',
    protein: 'medium',
    costBand: '₹',
    tags: ['Breakfast', 'Regional', 'Budget', 'Kid-friendly'],
    ingredients: [
      { qty: 2, unit: 'cup', item: 'idli rice (parboiled)', note: 'soaked 5 hours' },
      { qty: 0.5, unit: 'cup', item: 'whole white urad dal', note: 'soaked 5 hours' },
      { qty: 0.5, unit: 'tsp', item: 'fenugreek seeds', note: 'soaked with the urad dal' },
      { qty: 1.5, unit: 'tsp', item: 'salt', note: 'for the batter' },
      { qty: 1, unit: 'tsp', item: 'oil', note: 'to grease the idli plates' },
      { qty: 0.5, unit: 'cup', item: 'toor dal', note: 'rinsed' },
      { qty: 0.25, unit: 'tsp', item: 'turmeric powder' },
      { qty: 12, unit: 'piece', item: 'shallots', note: 'peeled, halved' },
      { qty: 2, unit: 'piece', item: 'tomatoes', note: 'chopped' },
      { qty: 2, unit: 'piece', item: 'green chillies', note: 'slit' },
      { qty: 1, unit: 'tsp', item: 'tamarind', note: 'soaked in 0.5 cup warm water, juice extracted' },
      { qty: 2, unit: 'tbsp', item: 'sambar powder' },
      { qty: 1.5, unit: 'tbsp', item: 'gingelly (sesame) oil' },
      { qty: 1, unit: 'tsp', item: 'mustard seeds' },
      { qty: 1, unit: 'pinch', item: 'asafoetida' },
      { qty: 2, unit: 'sprig', item: 'curry leaves' },
      { qty: null, unit: 'to taste', item: 'salt', note: 'for the sambar' },
      { qty: null, unit: 'to taste', item: 'coriander leaves', note: 'chopped' },
    ],
    steps: [
      {
        text: 'Rinse and soak the idli rice in one bowl, and the urad dal with the fenugreek in another, each covered with plenty of water, for 4–6 hours.',
        timerMin: 300,
      },
      {
        text: 'Grind the urad dal and fenugreek first, adding ice-cold water a little at a time, until the batter is very smooth, light and fluffy — a drop should float in water. Then grind the rice to a slightly grainy batter, like fine semolina.',
        timerMin: 20,
      },
      {
        text: 'Mix both batters with the salt using your hand for a minute, transfer to a large vessel (it will double), cover and leave in a warm place to ferment overnight until risen, bubbly and pleasantly sour-smelling.',
        timerMin: 480,
      },
      {
        text: 'For the sambar, pressure-cook the toor dal with 1.5 cups water and turmeric for 4 whistles (about 12 minutes) and mash until smooth.',
        timerMin: 12,
      },
      {
        text: 'Heat the gingelly oil, splutter the mustard seeds, add asafoetida and curry leaves, then the shallots and green chillies. Sauté until the shallots are translucent, add the tomatoes and cook until soft.',
        timerMin: 6,
      },
      {
        text: 'Add the tamarind water, sambar powder, salt and 1.5 cups water, simmer until the raw smell goes, then stir in the dal and simmer to a pourable consistency — tiffin sambar is thinner than rice sambar.',
        timerMin: 10,
      },
      {
        text: 'Bring 2 inches of water to a boil in an idli steamer. Gently stir the fermented batter without knocking out the air, grease the idli plates, and fill each mould three-quarters full.',
      },
      {
        text: 'Steam on medium-high heat until a knife inserted in the centre comes out clean. Rest 2 minutes, then scoop the idlis out with a wet spoon and serve hot with the sambar. Leftover batter keeps 3–4 days in the fridge.',
        timerMin: 12,
      },
    ],
    nutrition: { kcal: 390, proteinG: 13, carbsG: 70, fatG: 6, fibreG: 7 },
  },
  {
    id: 'ven-pongal',
    name: 'Ven Pongal',
    cuisine: 'Tamil',
    dietMode: 'vegetarian',
    description:
      'Creamy, peppery rice and moong dal cooked soft and finished with a ghee tempering of cumin, pepper, ginger and cashews — Tamil Nadu’s beloved temple-style breakfast.',
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 25,
    difficulty: 'easy',
    spice: 'mild',
    protein: 'medium',
    costBand: '₹',
    tags: ['Breakfast', 'Regional', 'One-pot', 'Kid-friendly'],
    ingredients: [
      { qty: 0.5, unit: 'cup', item: 'raw rice (ponni or sona masoori)' },
      { qty: 0.25, unit: 'cup', item: 'split yellow moong dal' },
      { qty: 3.5, unit: 'cup', item: 'water' },
      { qty: 0.25, unit: 'tsp', item: 'turmeric powder', note: 'optional' },
      { qty: 2.5, unit: 'tbsp', item: 'ghee' },
      { qty: 1, unit: 'tsp', item: 'black peppercorns', note: 'lightly crushed' },
      { qty: 1, unit: 'tsp', item: 'cumin seeds' },
      { qty: 1, unit: 'inch', item: 'ginger', note: 'finely chopped' },
      { qty: 1, unit: 'sprig', item: 'curry leaves' },
      { qty: 10, unit: 'piece', item: 'cashews', note: 'halved' },
      { qty: 1, unit: 'pinch', item: 'asafoetida' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'Dry-roast the moong dal in a pressure cooker on low heat, stirring, until it smells nutty and just turns light golden. Do not let it brown.',
        timerMin: 3,
      },
      {
        text: 'Add the rice and rinse the rice and dal together twice, then add 3.5 cups water, the turmeric and salt.',
      },
      {
        text: 'Pressure-cook on medium heat for 4 whistles (about 15 minutes) and let the pressure release naturally.',
        timerMin: 15,
      },
      {
        text: 'Open and mash the pongal well with a ladle until creamy. If it looks too thick, stir in 0.5 cup hot water over low heat — it firms up as it sits.',
      },
      {
        text: 'Heat the ghee in a small pan on low heat, fry the cashews until golden, then add the crushed pepper, cumin, ginger, curry leaves and asafoetida and let them sizzle for 30 seconds without burning.',
      },
      {
        text: 'Pour the ghee tempering over the pongal, mix well and serve hot with coconut chutney and sambar.',
      },
    ],
    nutrition: { kcal: 460, proteinG: 11, carbsG: 56, fatG: 21, fibreG: 4 },
  },
  {
    id: 'rava-upma',
    name: 'Karnataka Rava Upma',
    cuisine: 'Karnataka',
    dietMode: 'vegan',
    description:
      'Soft, fluffy roasted semolina cooked with vegetables and a crackling mustard-dal tempering, brightened with lemon — breakfast on the table in 25 minutes.',
    servings: 3,
    prepMinutes: 10,
    cookMinutes: 15,
    difficulty: 'easy',
    spice: 'mild',
    protein: 'low',
    costBand: '₹',
    tags: ['Breakfast', 'Quick', 'Budget', 'Tiffin box'],
    ingredients: [
      { qty: 1, unit: 'cup', item: 'Bombay rava (coarse semolina)' },
      { qty: 2.5, unit: 'cup', item: 'water' },
      { qty: 2, unit: 'tbsp', item: 'oil' },
      { qty: 1, unit: 'tsp', item: 'mustard seeds' },
      { qty: 1, unit: 'tsp', item: 'urad dal' },
      { qty: 1, unit: 'tsp', item: 'chana dal' },
      { qty: 8, unit: 'piece', item: 'cashews', note: 'halved' },
      { qty: 1, unit: 'sprig', item: 'curry leaves' },
      { qty: 2, unit: 'piece', item: 'green chillies', note: 'slit' },
      { qty: 1, unit: 'inch', item: 'ginger', note: 'finely chopped' },
      { qty: 1, unit: 'piece', item: 'medium onion', note: 'finely chopped' },
      { qty: 1, unit: 'piece', item: 'small carrot', note: 'finely diced' },
      { qty: 0.25, unit: 'cup', item: 'green peas' },
      { qty: 1, unit: 'tsp', item: 'sugar', note: 'optional, Karnataka style' },
      { qty: 1, unit: 'tbsp', item: 'lemon juice' },
      { qty: null, unit: 'to taste', item: 'salt' },
      { qty: 2, unit: 'tbsp', item: 'coriander leaves', note: 'chopped' },
    ],
    steps: [
      {
        text: 'Dry-roast the rava in a heavy kadai on low-medium heat, stirring constantly, until it is aromatic and grainy but still pale. Transfer to a plate.',
        timerMin: 5,
      },
      {
        text: 'In the same kadai heat the oil, add the mustard seeds and let them splutter, then add the urad dal, chana dal and cashews and fry until golden.',
      },
      {
        text: 'Add the curry leaves, green chillies, ginger and onion and sauté until the onion is soft and translucent. Add the carrot and peas and cook for 2 minutes.',
        timerMin: 4,
      },
      {
        text: 'Pour in 2.5 cups water with the salt and sugar, and bring it to a rolling boil.',
      },
      {
        text: 'Lower the heat and add the roasted rava in a thin stream with one hand while stirring continuously with the other, so no lumps form.',
      },
      {
        text: 'Cover and cook on the lowest heat until the rava has absorbed all the water and is soft and fluffy, then turn off and rest covered for 2 minutes.',
        timerMin: 3,
      },
      {
        text: 'Stir in the lemon juice and coriander, fluff gently and serve hot with coconut chutney.',
      },
    ],
    nutrition: { kcal: 335, proteinG: 8, carbsG: 50, fatG: 11, fibreG: 4 },
  },
  {
    id: 'kanda-poha',
    name: 'Kanda Poha',
    cuisine: 'Maharashtrian',
    dietMode: 'vegan',
    description:
      'Light, fluffy flattened rice tossed with onions, peanuts, turmeric and curry leaves and finished with lemon — Maharashtra’s everyday breakfast in 20 minutes.',
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 10,
    difficulty: 'easy',
    spice: 'mild',
    protein: 'low',
    costBand: '₹',
    tags: ['Breakfast', 'Quick', 'Budget', 'Kid-friendly'],
    ingredients: [
      { qty: 1.5, unit: 'cup', item: 'thick poha (flattened rice)' },
      { qty: 1.5, unit: 'tbsp', item: 'groundnut oil' },
      { qty: 2, unit: 'tbsp', item: 'raw peanuts' },
      { qty: 1, unit: 'tsp', item: 'mustard seeds' },
      { qty: 0.5, unit: 'tsp', item: 'cumin seeds' },
      { qty: 1, unit: 'sprig', item: 'curry leaves' },
      { qty: 2, unit: 'piece', item: 'green chillies', note: 'finely chopped' },
      { qty: 1, unit: 'piece', item: 'large onion', note: 'finely chopped' },
      { qty: 0.25, unit: 'tsp', item: 'turmeric powder' },
      { qty: 1, unit: 'tsp', item: 'sugar' },
      { qty: 1, unit: 'tbsp', item: 'lemon juice' },
      { qty: null, unit: 'to taste', item: 'salt' },
      { qty: 2, unit: 'tbsp', item: 'coriander leaves', note: 'chopped' },
      { qty: 2, unit: 'tbsp', item: 'fresh grated coconut', note: 'optional, to garnish' },
    ],
    steps: [
      {
        text: 'Put the poha in a sieve and rinse under running water for 10–15 seconds, tossing, until just softened. Drain, sprinkle with the salt and sugar, mix gently and leave for 5 minutes so the flakes soften without turning mushy.',
        timerMin: 5,
      },
      {
        text: 'Heat the oil in a kadai on medium heat and fry the peanuts until they are crunchy and browned in spots. Lift them out with a slotted spoon.',
        timerMin: 3,
      },
      {
        text: 'In the same oil, splutter the mustard seeds, then add cumin, curry leaves and green chillies and fry for a few seconds.',
      },
      {
        text: 'Add the onion and sauté until soft and translucent but not browned, then stir in the turmeric.',
        timerMin: 3,
      },
      {
        text: 'Add the poha and peanuts and toss gently with a spatula until the poha is evenly yellow. Cover and steam on low heat for 2 minutes so it becomes soft and hot throughout.',
        timerMin: 2,
      },
      {
        text: 'Turn off the heat, drizzle over the lemon juice, and finish with coriander and grated coconut. Serve immediately.',
      },
    ],
    nutrition: { kcal: 390, proteinG: 7, carbsG: 56, fatG: 15, fibreG: 4 },
  },
  {
    id: 'dal-tadka',
    name: 'Dal Tadka',
    cuisine: 'North Indian',
    dietMode: 'vegetarian',
    description:
      'Soft-cooked toor dal with an onion-tomato masala, finished with a sizzling ghee tadka of cumin, garlic and red chilli — the dhaba classic at home.',
    servings: 3,
    prepMinutes: 10,
    cookMinutes: 30,
    difficulty: 'easy',
    spice: 'medium',
    protein: 'medium',
    costBand: '₹',
    tags: ['Budget', 'Kid-friendly', 'Tiffin box'],
    ingredients: [
      { qty: 0.75, unit: 'cup', item: 'toor dal', note: 'rinsed and soaked 20 minutes' },
      { qty: 2.5, unit: 'cup', item: 'water' },
      { qty: 0.25, unit: 'tsp', item: 'turmeric powder' },
      { qty: 1, unit: 'tbsp', item: 'ghee', note: 'for the masala' },
      { qty: 1, unit: 'piece', item: 'medium onion', note: 'finely chopped' },
      { qty: 1, unit: 'tsp', item: 'ginger', note: 'grated' },
      { qty: 1, unit: 'piece', item: 'green chilli', note: 'slit' },
      { qty: 1, unit: 'piece', item: 'large tomato', note: 'finely chopped' },
      { qty: 0.5, unit: 'tsp', item: 'coriander powder' },
      { qty: 0.25, unit: 'tsp', item: 'garam masala' },
      { qty: 1, unit: 'tbsp', item: 'ghee', note: 'for the tadka' },
      { qty: 1, unit: 'tsp', item: 'cumin seeds' },
      { qty: 4, unit: 'clove', item: 'garlic', note: 'thinly sliced' },
      { qty: 2, unit: 'piece', item: 'dry red chillies' },
      { qty: 1, unit: 'pinch', item: 'asafoetida' },
      { qty: 0.5, unit: 'tsp', item: 'Kashmiri red chilli powder' },
      { qty: null, unit: 'to taste', item: 'salt' },
      { qty: 2, unit: 'tbsp', item: 'coriander leaves', note: 'chopped' },
    ],
    steps: [
      {
        text: 'Pressure-cook the soaked toor dal with 2.5 cups water, turmeric and a little salt for 4 whistles (about 12 minutes). Once the pressure drops, whisk it until smooth.',
        timerMin: 12,
      },
      {
        text: 'Heat 1 tbsp ghee in a pan, add the onion and sauté on medium heat until light golden, then add the ginger and green chilli and cook for 1 minute.',
        timerMin: 5,
      },
      {
        text: 'Add the tomato, coriander powder and salt, and cook until the tomato is completely soft and mushy.',
        timerMin: 4,
      },
      {
        text: 'Pour in the cooked dal and about 0.5 cup hot water, bring to a boil and simmer on low heat until it is creamy and flowing, not thick like a paste. Stir in the garam masala.',
        timerMin: 6,
      },
      {
        text: 'For the tadka, heat 1 tbsp ghee in a small pan until hot, add the cumin and let it crackle, then the garlic and fry until light golden. Add the dry red chillies and asafoetida, turn off the heat and stir in the chilli powder.',
      },
      {
        text: 'Immediately pour the sizzling tadka over the dal, garnish with coriander and serve hot with jeera rice or rotis.',
      },
    ],
    nutrition: { kcal: 280, proteinG: 12, carbsG: 34, fatG: 10, fibreG: 8 },
  },
  {
    id: 'palak-paneer',
    name: 'Palak Paneer',
    cuisine: 'Punjabi',
    dietMode: 'vegetarian',
    description:
      'Soft paneer cubes in a bright green, garlicky spinach gravy with a touch of cream — rich in protein and far greener than the restaurant version.',
    servings: 3,
    prepMinutes: 20,
    cookMinutes: 25,
    difficulty: 'medium',
    spice: 'mild',
    protein: 'high',
    costBand: '₹₹',
    tags: ['High protein', 'Regional', 'Kid-friendly'],
    ingredients: [
      { qty: 500, unit: 'g', item: 'spinach (palak)', note: 'washed well, thick stems removed' },
      { qty: 200, unit: 'g', item: 'paneer', note: 'cut into 1-inch cubes' },
      { qty: 2, unit: 'piece', item: 'green chillies' },
      { qty: 1, unit: 'tbsp', item: 'ghee' },
      { qty: 1, unit: 'tbsp', item: 'oil' },
      { qty: 1, unit: 'tsp', item: 'cumin seeds' },
      { qty: 1, unit: 'piece', item: 'medium onion', note: 'finely chopped' },
      { qty: 1, unit: 'inch', item: 'ginger', note: 'grated' },
      { qty: 4, unit: 'clove', item: 'garlic', note: 'finely chopped' },
      { qty: 1, unit: 'piece', item: 'medium tomato', note: 'finely chopped' },
      { qty: 0.25, unit: 'tsp', item: 'turmeric powder' },
      { qty: 1, unit: 'tsp', item: 'coriander powder' },
      { qty: 0.5, unit: 'tsp', item: 'garam masala' },
      { qty: 1, unit: 'tsp', item: 'kasuri methi', note: 'crushed' },
      { qty: 2, unit: 'tbsp', item: 'fresh cream' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'Bring a large pot of water to a boil, add the spinach and blanch for 2 minutes until just wilted, then transfer immediately to a bowl of ice-cold water to lock in the green colour.',
        timerMin: 2,
      },
      {
        text: 'Drain the spinach, squeeze lightly, and blend it with the green chillies to a smooth purée, adding a few tablespoons of water only if needed.',
      },
      {
        text: 'Soak the paneer cubes in hot salted water for 10 minutes to keep them soft.',
        timerMin: 10,
      },
      {
        text: 'Heat the ghee and oil in a pan, add the cumin, then the onion, and sauté on medium heat until golden. Add the ginger and garlic and fry until the raw smell goes.',
        timerMin: 7,
      },
      {
        text: 'Add the tomato, turmeric, coriander powder and salt and cook until the tomato is soft and the fat starts to separate.',
        timerMin: 4,
      },
      {
        text: 'Stir in the spinach purée and 0.25 cup water and simmer for 3–4 minutes only — cooking it longer turns the gravy dull olive green.',
        timerMin: 4,
      },
      {
        text: 'Add the drained paneer, garam masala and crushed kasuri methi, simmer 2 minutes, then turn off the heat and swirl in the cream. Serve hot with rotis or jeera rice.',
        timerMin: 2,
      },
    ],
    nutrition: { kcal: 345, proteinG: 17, carbsG: 14, fatG: 25, fibreG: 6 },
  },
  {
    id: 'hyderabadi-veg-dum-biryani',
    name: 'Hyderabadi Veg Dum Biryani',
    cuisine: 'Telangana',
    dietMode: 'vegetarian',
    description:
      'Long-grain basmati layered over curd-marinated vegetables with fried onions, mint and saffron, then sealed and slow-cooked on dum the Hyderabadi way.',
    servings: 4,
    prepMinutes: 40,
    cookMinutes: 50,
    difficulty: 'involved',
    spice: 'medium',
    protein: 'medium',
    costBand: '₹₹',
    tags: ['Regional', 'Weekend'],
    ingredients: [
      { qty: 1.5, unit: 'cup', item: 'aged basmati rice', note: 'rinsed and soaked 30 minutes' },
      { qty: 400, unit: 'g', item: 'mixed vegetables (carrot, beans, cauliflower, potato, peas)', note: 'cut into 1-inch pieces' },
      { qty: 0.75, unit: 'cup', item: 'thick curd', note: 'whisked' },
      { qty: 1, unit: 'tbsp', item: 'ginger-garlic paste' },
      { qty: 1.5, unit: 'tsp', item: 'red chilli powder' },
      { qty: 0.25, unit: 'tsp', item: 'turmeric powder' },
      { qty: 1.5, unit: 'tsp', item: 'biryani masala' },
      { qty: 3, unit: 'piece', item: 'green chillies', note: 'slit' },
      { qty: 1, unit: 'handful', item: 'mint leaves' },
      { qty: 1, unit: 'handful', item: 'coriander leaves', note: 'chopped' },
      { qty: 2, unit: 'piece', item: 'large onions', note: 'thinly sliced' },
      { qty: 4, unit: 'tbsp', item: 'oil', note: 'for frying onions' },
      { qty: 2, unit: 'tbsp', item: 'ghee' },
      { qty: 1, unit: 'tbsp', item: 'lemon juice' },
      { qty: 2, unit: 'piece', item: 'bay leaves' },
      { qty: 4, unit: 'piece', item: 'green cardamom' },
      { qty: 4, unit: 'piece', item: 'cloves' },
      { qty: 1, unit: 'inch', item: 'cinnamon stick' },
      { qty: 1, unit: 'tsp', item: 'shahi jeera (caraway)' },
      { qty: 1, unit: 'pinch', item: 'saffron', note: 'soaked in 2 tbsp warm milk' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'Rinse the basmati until the water runs clear and soak it for 30 minutes. Meanwhile, soak the saffron in 2 tbsp warm milk.',
        timerMin: 30,
      },
      {
        text: 'Heat the oil in a heavy-bottomed pot and fry the sliced onions on medium heat, stirring often, until deep golden brown and crisp. Lift out half onto a paper towel for layering and leave the rest (with the oil) in the pot.',
        timerMin: 15,
      },
      {
        text: 'Marinate the vegetables with the curd, ginger-garlic paste, chilli powder, turmeric, biryani masala, green chillies, half the mint and coriander, lemon juice and salt for at least 20 minutes.',
        timerMin: 20,
      },
      {
        text: 'Add the marinated vegetables to the pot with the onions and oil, and cook on medium heat, stirring, until the vegetables are about 80% cooked and the masala thickens.',
        timerMin: 10,
      },
      {
        text: 'Meanwhile bring 8 cups of water to a rolling boil with the bay leaves, cardamom, cloves, cinnamon, shahi jeera and 1.5 tbsp salt. Add the drained rice and boil until 70% cooked — the grain should break when pressed but still have a firm core. Drain immediately.',
        timerMin: 5,
      },
      {
        text: 'Spread the rice evenly over the vegetables. Top with the remaining fried onions, mint and coriander, drizzle the saffron milk and the ghee over the rice.',
      },
      {
        text: 'Seal the pot with a tight lid (lined with foil or sealed with dough). Cook on high heat for 3 minutes, then place the pot on a hot tawa on the lowest heat and cook on dum.',
        timerMin: 25,
      },
      {
        text: 'Turn off and rest sealed for 10 minutes. Open, and serve by scooping from the side down to the bottom so each portion gets rice and vegetables, with mirchi ka salan or raita.',
        timerMin: 10,
      },
    ],
    nutrition: { kcal: 530, proteinG: 10, carbsG: 76, fatG: 21, fibreG: 6 },
  },
  {
    id: 'aloo-paratha',
    name: 'Punjabi Aloo Paratha',
    cuisine: 'Punjabi',
    dietMode: 'vegetarian',
    description:
      'Whole-wheat flatbreads stuffed with a spiced potato filling of green chilli, ajwain and amchur, roasted with ghee until golden and crisp.',
    servings: 4,
    prepMinutes: 30,
    cookMinutes: 35,
    difficulty: 'medium',
    spice: 'medium',
    protein: 'medium',
    costBand: '₹',
    tags: ['Breakfast', 'Regional', 'Kid-friendly', 'Tiffin box'],
    ingredients: [
      { qty: 2, unit: 'cup', item: 'whole-wheat flour (atta)', note: 'plus extra for dusting' },
      { qty: 0.75, unit: 'cup', item: 'water', note: 'approximately, for the dough' },
      { qty: 1, unit: 'tsp', item: 'oil', note: 'for the dough' },
      { qty: 4, unit: 'piece', item: 'medium potatoes', note: 'about 500 g' },
      { qty: 2, unit: 'piece', item: 'green chillies', note: 'finely chopped' },
      { qty: 1, unit: 'inch', item: 'ginger', note: 'grated' },
      { qty: 3, unit: 'tbsp', item: 'coriander leaves', note: 'finely chopped' },
      { qty: 0.5, unit: 'tsp', item: 'ajwain (carom seeds)' },
      { qty: 1, unit: 'tsp', item: 'amchur (dry mango powder)' },
      { qty: 0.5, unit: 'tsp', item: 'garam masala' },
      { qty: 0.5, unit: 'tsp', item: 'red chilli powder' },
      { qty: 0.5, unit: 'tsp', item: 'roasted cumin powder' },
      { qty: 3, unit: 'tbsp', item: 'ghee', note: 'for roasting' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'Mix the atta with a pinch of salt and the oil, add water gradually and knead into a soft, smooth dough. Cover and rest.',
        timerMin: 20,
      },
      {
        text: 'Meanwhile pressure-cook the potatoes with water to cover for 3 whistles (about 10 minutes). Cool until warm, peel, and grate or mash until completely smooth with no lumps.',
        timerMin: 10,
      },
      {
        text: 'Mix the potatoes with the green chillies, ginger, coriander, ajwain (crushed between your palms), amchur, garam masala, chilli powder, cumin powder and salt. Divide into 8 equal balls.',
      },
      {
        text: 'Divide the dough into 8 balls. Roll one into a 4-inch circle, place a potato ball in the centre, bring the edges up and pinch them together to seal, then flatten gently.',
      },
      {
        text: 'Dust with flour and roll out gently into a 7-inch paratha, applying even pressure so the filling does not burst through.',
      },
      {
        text: 'Place on a hot tawa over medium heat and cook until small bubbles appear, flip, and cook the other side for 30 seconds.',
        timerMin: 1,
      },
      {
        text: 'Spread 1 tsp ghee on each side and roast, pressing the edges with a spatula, until both sides have golden-brown spots and the paratha is crisp, about 1–2 minutes per side. Repeat with the rest and serve hot with curd and pickle.',
        timerMin: 3,
      },
    ],
    nutrition: { kcal: 420, proteinG: 10, carbsG: 65, fatG: 13, fibreG: 9 },
  },
  {
    id: 'pesarattu',
    name: 'Andhra Pesarattu',
    cuisine: 'Andhra',
    dietMode: 'vegan',
    description:
      'Crisp, protein-rich green moong dosas spiked with ginger, green chilli and cumin, topped with onion — a classic Andhra breakfast with no fermenting needed.',
    servings: 3,
    prepMinutes: 15,
    cookMinutes: 25,
    difficulty: 'easy',
    spice: 'medium',
    protein: 'high',
    costBand: '₹',
    tags: ['Breakfast', 'High protein', 'Regional', 'Budget'],
    ingredients: [
      { qty: 1, unit: 'cup', item: 'whole green moong', note: 'soaked 6 hours' },
      { qty: 2, unit: 'tbsp', item: 'raw rice', note: 'soaked with the moong, for crispness' },
      { qty: 1, unit: 'inch', item: 'ginger', note: 'roughly chopped' },
      { qty: 3, unit: 'piece', item: 'green chillies' },
      { qty: 1, unit: 'tsp', item: 'cumin seeds' },
      { qty: 0.75, unit: 'cup', item: 'water', note: 'approximately, for grinding' },
      { qty: 1, unit: 'piece', item: 'medium onion', note: 'finely chopped, for topping' },
      { qty: 2, unit: 'tbsp', item: 'coriander leaves', note: 'finely chopped' },
      { qty: 3, unit: 'tbsp', item: 'oil', note: 'for cooking' },
      { qty: null, unit: 'to taste', item: 'salt' },
    ],
    steps: [
      {
        text: 'Rinse the whole green moong and rice together and soak them in plenty of water for at least 6 hours or overnight.',
        timerMin: 360,
      },
      {
        text: 'Drain and grind with the ginger, green chillies, cumin and salt, adding water gradually, into a smooth batter that is slightly thicker than dosa batter. No fermentation is needed.',
      },
      {
        text: 'Heat a cast-iron or non-stick tawa on medium-high heat and wipe it with a little oil. Sprinkle a few drops of water — if they sizzle away immediately, the tawa is ready.',
      },
      {
        text: 'Pour a ladle of batter in the centre and spread it quickly in outward circles into a thin round. Sprinkle some onion and coriander on top and press them in lightly with the ladle.',
      },
      {
        text: 'Drizzle 1 tsp oil around the edges and cook on medium heat until the underside is golden and crisp and the edges lift away from the tawa.',
        timerMin: 2,
      },
      {
        text: 'Flip and cook the onion side for 30–40 seconds, then fold and serve hot with ginger chutney or upma. Wipe the tawa and repeat with the remaining batter.',
      },
    ],
    nutrition: { kcal: 400, proteinG: 17, carbsG: 52, fatG: 15, fibreG: 12 },
  },
]
